pub fn emit_x86_runtime(out: &mut String) {
    // alya_concat
    out.push_str("alya_concat:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    push %ebx\n");
    out.push_str("    mov 8(%ebp), %esi\n");
    out.push_str("    mov 12(%ebp), %edx\n");
    out.push_str("    mov $alya_str_buf, %ecx\n");
    out.push_str("    mov alya_str_idx, %ebx\n");
    out.push_str("    cmp $48000, %ebx\n");
    out.push_str("    jl .L_x86_concat_ok\n");
    out.push_str("    xor %ebx, %ebx\n");
    out.push_str(".L_x86_concat_ok:\n");
    out.push_str("    lea (%ecx, %ebx), %edi\n");
    out.push_str("    mov %edi, %eax\n");
    out.push_str(".L_x86_copy1:\n");
    out.push_str("    movb (%esi), %bl\n");
    out.push_str("    test %bl, %bl\n");
    out.push_str("    jz .L_x86_copy2_start\n");
    out.push_str("    movb %cl, (%edi)\n");
    out.push_str("    inc %esi\n");
    out.push_str("    inc %edi\n");
    out.push_str("    jmp .L_x86_copy1\n");
    out.push_str(".L_x86_copy2_start:\n");
    out.push_str("    mov %edx, %esi\n");
    out.push_str(".L_x86_copy2:\n");
    out.push_str("    movb (%esi), %bl\n");
    out.push_str("    test %bl, %bl\n");
    out.push_str("    jz .L_x86_concat_end\n");
    out.push_str("    movb %cl, (%edi)\n");
    out.push_str("    inc %esi\n");
    out.push_str("    inc %edi\n");
    out.push_str("    jmp .L_x86_copy2\n");
    out.push_str(".L_x86_concat_end:\n");
    out.push_str("    movb $0, (%edi)\n");
    out.push_str("    inc %edi\n");
    out.push_str("    sub %ecx, %edi\n");
    out.push_str("    add $3, %edi\n");
    out.push_str("    and $-4, %edi\n");
    out.push_str("    mov %edi, alya_str_idx\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_len
    out.push_str("fn_len:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    mov 8(%ebp), %edx\n");
    out.push_str("    xor %eax, %eax\n");
    out.push_str(".L_x86_len_loop:\n");
    out.push_str("    cmpb $0, (%edx, %eax)\n");
    out.push_str("    je .L_x86_len_end\n");
    out.push_str("    inc %eax\n");
    out.push_str("    jmp .L_x86_len_loop\n");
    out.push_str(".L_x86_len_end:\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_abs
    out.push_str("fn_abs:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    mov 8(%ebp), %eax\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jns .L_x86_abs_end\n");
    out.push_str("    neg %eax\n");
    out.push_str(".L_x86_abs_end:\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_min
    out.push_str("fn_min:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    mov 8(%ebp), %eax\n");
    out.push_str("    mov 12(%ebp), %edx\n");
    out.push_str("    cmp %edx, %eax\n");
    out.push_str("    jle .L_x86_min_end\n");
    out.push_str("    mov %edx, %eax\n");
    out.push_str(".L_x86_min_end:\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_max
    out.push_str("fn_max:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    mov 8(%ebp), %eax\n");
    out.push_str("    mov 12(%ebp), %edx\n");
    out.push_str("    cmp %edx, %eax\n");
    out.push_str("    jge .L_x86_max_end\n");
    out.push_str("    mov %edx, %eax\n");
    out.push_str(".L_x86_max_end:\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_sqrt
    out.push_str("fn_sqrt:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    mov 8(%ebp), %ecx\n");
    out.push_str("    test %ecx, %ecx\n");
    out.push_str("    jle .L_x86_sqrt_zero\n");
    out.push_str("    cmp $4, %ecx\n");
    out.push_str("    jl .L_x86_sqrt_one\n");
    out.push_str("    push %ebx\n");
    out.push_str("    mov %ecx, %ebx\n");
    out.push_str("    shr $1, %ebx\n");
    out.push_str(".L_x86_sqrt_loop:\n");
    out.push_str("    mov %ecx, %eax\n");
    out.push_str("    xor %edx, %edx\n");
    out.push_str("    div %ebx\n");
    out.push_str("    add %ebx, %eax\n");
    out.push_str("    shr $1, %eax\n");
    out.push_str("    cmp %ebx, %eax\n");
    out.push_str("    jge .L_x86_sqrt_done\n");
    out.push_str("    mov %eax, %ebx\n");
    out.push_str("    jmp .L_x86_sqrt_loop\n");
    out.push_str(".L_x86_sqrt_done:\n");
    out.push_str("    mov %ebx, %eax\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    jmp .L_x86_sqrt_end\n");
    out.push_str(".L_x86_sqrt_one:\n");
    out.push_str("    mov $1, %eax\n");
    out.push_str("    jmp .L_x86_sqrt_end\n");
    out.push_str(".L_x86_sqrt_zero:\n");
    out.push_str("    xor %eax, %eax\n");
    out.push_str(".L_x86_sqrt_end:\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_pow
    out.push_str("fn_pow:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    mov 8(%ebp), %ecx\n");
    out.push_str("    mov 12(%ebp), %edx\n");
    out.push_str("    test %edx, %edx\n");
    out.push_str("    js .L_x86_pow_zero\n");
    out.push_str("    mov $1, %eax\n");
    out.push_str(".L_x86_pow_loop:\n");
    out.push_str("    test %edx, %edx\n");
    out.push_str("    jle .L_x86_pow_end\n");
    out.push_str("    test $1, %edx\n");
    out.push_str("    jz .L_x86_pow_even\n");
    out.push_str("    imul %ecx, %eax\n");
    out.push_str(".L_x86_pow_even:\n");
    out.push_str("    imul %ecx, %ecx\n");
    out.push_str("    shr $1, %edx\n");
    out.push_str("    jmp .L_x86_pow_loop\n");
    out.push_str(".L_x86_pow_zero:\n");
    out.push_str("    xor %eax, %eax\n");
    out.push_str(".L_x86_pow_end:\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_exit
    out.push_str("fn_exit:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push 8(%ebp)\n");
    out.push_str("    call exit\n\n");

    // fn_ask
    out.push_str("fn_ask:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    push %ebx\n");
    out.push_str("    mov 8(%ebp), %eax\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jz .L_x86_ask_read\n");
    out.push_str("    push %eax\n");
    out.push_str("    push $alya_fmt_prompt\n");
    out.push_str("    call printf\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    push $0\n");
    out.push_str("    call fflush\n");
    out.push_str("    add $4, %esp\n");
    out.push_str(".L_x86_ask_read:\n");
    out.push_str("    mov $alya_str_buf, %ecx\n");
    out.push_str("    mov alya_str_idx, %ebx\n");
    out.push_str("    cmp $48000, %ebx\n");
    out.push_str("    jl .L_x86_ask_buf_ok\n");
    out.push_str("    xor %ebx, %ebx\n");
    out.push_str(".L_x86_ask_buf_ok:\n");
    out.push_str("    lea (%ecx, %ebx), %esi\n");
    out.push_str("    mov %esi, %edi\n");
    out.push_str(".L_x86_ask_loop:\n");
    out.push_str("    call getchar\n");
    out.push_str("    cmp $-1, %eax\n");
    out.push_str("    je .L_x86_ask_done\n");
    out.push_str("    cmp $10, %eax\n");
    out.push_str("    je .L_x86_ask_done\n");
    out.push_str("    cmp $13, %eax\n");
    out.push_str("    je .L_x86_ask_loop\n");
    out.push_str("    movb %al, (%edi)\n");
    out.push_str("    inc %edi\n");
    out.push_str("    jmp .L_x86_ask_loop\n");
    out.push_str(".L_x86_ask_done:\n");
    out.push_str("    movb $0, (%edi)\n");
    out.push_str("    inc %edi\n");
    out.push_str("    sub %ecx, %edi\n");
    out.push_str("    add $3, %edi\n");
    out.push_str("    and $-4, %edi\n");
    out.push_str("    mov %edi, alya_str_idx\n");
    out.push_str("    mov %esi, %eax\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // alya_error_div_zero
    out.push_str("alya_error_div_zero:\n");
    out.push_str("    mov alya_catch_idx, %ecx\n");
    out.push_str("    test %ecx, %ecx\n");
    out.push_str("    jz .L_x86_fatal_div_zero\n");
    out.push_str("    dec %ecx\n");
    out.push_str("    mov %ecx, alya_catch_idx\n");
    out.push_str("    mov $alya_str_div_zero, %eax\n");
    out.push_str("    mov %eax, alya_err_msg\n");
    out.push_str("    mov $alya_catch_stack_sp, %edx\n");
    out.push_str("    mov (%edx, %ecx, 4), %esp\n");
    out.push_str("    mov $alya_catch_stack_bp, %edx\n");
    out.push_str("    mov (%edx, %ecx, 4), %ebp\n");
    out.push_str("    mov $alya_catch_stack_handler, %edx\n");
    out.push_str("    mov (%edx, %ecx, 4), %eax\n");
    out.push_str("    jmp *%eax\n");
    out.push_str(".L_x86_fatal_div_zero:\n");
    out.push_str("    and $-16, %esp\n");
    out.push_str("    push $alya_fmt_div_zero\n");
    out.push_str("    call printf\n");
    out.push_str("    push $1\n");
    out.push_str("    call exit\n\n");

    // alya_array_new
    out.push_str("alya_array_new:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov 8(%ebp), %esi\n");
    out.push_str("    mov %esi, %ebx\n");
    out.push_str("    cmp $8, %ebx\n");
    out.push_str("    jge .L_x86_new_cap_ok\n");
    out.push_str("    mov $8, %ebx\n");
    out.push_str("    jmp .L_x86_new_alloc_hdr\n");
    out.push_str(".L_x86_new_cap_ok:\n");
    out.push_str("    shl $1, %ebx\n");
    out.push_str(".L_x86_new_alloc_hdr:\n");
    out.push_str("    push $12\n");
    out.push_str("    push $1\n");
    out.push_str("    call calloc\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    mov %eax, %edi\n");
    out.push_str("    push $4\n");
    out.push_str("    push %ebx\n");
    out.push_str("    call calloc\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    mov %esi, (%edi)\n");
    out.push_str("    mov %ebx, 4(%edi)\n");
    out.push_str("    mov %eax, 8(%edi)\n");
    out.push_str("    mov %edi, %eax\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // alya_array_push
    out.push_str("alya_array_push:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov 8(%ebp), %esi\n");
    out.push_str("    mov 12(%ebp), %edi\n");
    out.push_str("    mov (%esi), %eax\n");
    out.push_str("    mov 4(%esi), %ebx\n");
    out.push_str("    cmp %ebx, %eax\n");
    out.push_str("    jl .L_x86_push_store\n");
    out.push_str("    test %ebx, %ebx\n");
    out.push_str("    jnz .L_x86_push_double\n");
    out.push_str("    mov $8, %ebx\n");
    out.push_str("    jmp .L_x86_push_realloc\n");
    out.push_str(".L_x86_push_double:\n");
    out.push_str("    shl $1, %ebx\n");
    out.push_str(".L_x86_push_realloc:\n");
    out.push_str("    mov %ebx, 4(%esi)\n");
    out.push_str("    lea (, %ebx, 4), %eax\n");
    out.push_str("    push %eax\n");
    out.push_str("    push 8(%esi)\n");
    out.push_str("    call realloc\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    mov %eax, 8(%esi)\n");
    out.push_str(".L_x86_push_store:\n");
    out.push_str("    mov 8(%esi), %edx\n");
    out.push_str("    mov (%esi), %eax\n");
    out.push_str("    mov %edi, (%edx, %eax, 4)\n");
    out.push_str("    inc %eax\n");
    out.push_str("    mov %eax, (%esi)\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // alya_array_pop
    out.push_str("alya_array_pop:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %ebx\n");
    out.push_str("    mov 8(%ebp), %esi\n");
    out.push_str("    mov (%esi), %eax\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jle alya_error_index_out_of_bounds\n");
    out.push_str("    dec %eax\n");
    out.push_str("    mov %eax, (%esi)\n");
    out.push_str("    mov 8(%esi), %edx\n");
    out.push_str("    mov (%edx, %eax, 4), %eax\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    pop %esi\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // alya_print_array
    out.push_str("alya_print_array:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov 8(%ebp), %esi\n");
    out.push_str("    test %esi, %esi\n");
    out.push_str("    jnz .L_x86_arr_not_null\n");
    out.push_str("    push $alya_fmt_arr_empty\n");
    out.push_str("    call printf\n");
    out.push_str("    add $4, %esp\n");
    out.push_str("    jmp .L_x86_arr_exit\n");
    out.push_str(".L_x86_arr_not_null:\n");
    out.push_str("    mov (%esi), %edi\n");
    out.push_str("    push $alya_fmt_arr_open\n");
    out.push_str("    call printf\n");
    out.push_str("    add $4, %esp\n");
    out.push_str("    xor %ebx, %ebx\n");
    out.push_str(".L_x86_arr_loop:\n");
    out.push_str("    cmp %edi, %ebx\n");
    out.push_str("    jge .L_x86_arr_close_call\n");
    out.push_str("    test %ebx, %ebx\n");
    out.push_str("    jz .L_x86_arr_print_elem\n");
    out.push_str("    push $alya_fmt_arr_comma\n");
    out.push_str("    call printf\n");
    out.push_str("    add $4, %esp\n");
    out.push_str(".L_x86_arr_print_elem:\n");
    out.push_str("    mov 8(%esi), %edx\n");
    out.push_str("    push (%edx, %ebx, 4)\n");
    out.push_str("    push $alya_fmt_arr_elem\n");
    out.push_str("    call printf\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    inc %ebx\n");
    out.push_str("    jmp .L_x86_arr_loop\n");
    out.push_str(".L_x86_arr_close_call:\n");
    out.push_str("    push $alya_fmt_arr_close\n");
    out.push_str("    call printf\n");
    out.push_str("    add $4, %esp\n");
    out.push_str(".L_x86_arr_exit:\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // alya_struct_new
    out.push_str("alya_struct_new:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    mov 8(%ebp), %esi\n");
    out.push_str("    mov 12(%ebp), %ebx\n");
    out.push_str("    lea 1(%ebx), %eax\n");
    out.push_str("    push $4\n");
    out.push_str("    push %eax\n");
    out.push_str("    call calloc\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    mov %esi, (%eax)\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // alya_print_struct
    out.push_str("alya_print_struct:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov 8(%ebp), %esi\n");
    out.push_str("    test %esi, %esi\n");
    out.push_str("    jnz .L_x86_struct_not_null\n");
    out.push_str("    push $alya_fmt_struct_null\n");
    out.push_str("    call printf\n");
    out.push_str("    add $4, %esp\n");
    out.push_str("    jmp .L_x86_struct_exit\n");
    out.push_str(".L_x86_struct_not_null:\n");
    out.push_str("    mov (%esi), %edi\n");
    out.push_str("    push (%edi)\n");
    out.push_str("    push $alya_fmt_struct_open\n");
    out.push_str("    call printf\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    xor %ebx, %ebx\n");
    out.push_str(".L_x86_struct_loop:\n");
    out.push_str("    cmp 4(%edi), %ebx\n");
    out.push_str("    jge .L_x86_struct_close\n");
    out.push_str("    test %ebx, %ebx\n");
    out.push_str("    jz .L_x86_struct_print_f\n");
    out.push_str("    push $alya_fmt_struct_comma\n");
    out.push_str("    call printf\n");
    out.push_str("    add $4, %esp\n");
    out.push_str(".L_x86_struct_print_f:\n");
    out.push_str("    push 4(%esi, %ebx, 4)\n");
    out.push_str("    push 8(%edi, %ebx, 4)\n");
    out.push_str("    push $alya_fmt_struct_field\n");
    out.push_str("    call printf\n");
    out.push_str("    add $12, %esp\n");
    out.push_str("    inc %ebx\n");
    out.push_str("    jmp .L_x86_struct_loop\n");
    out.push_str(".L_x86_struct_close:\n");
    out.push_str("    push $alya_fmt_struct_close\n");
    out.push_str("    call printf\n");
    out.push_str("    add $4, %esp\n");
    out.push_str(".L_x86_struct_exit:\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // alya_error_index_out_of_bounds
    out.push_str("alya_error_index_out_of_bounds:\n");
    out.push_str("    mov alya_catch_idx, %ecx\n");
    out.push_str("    test %ecx, %ecx\n");
    out.push_str("    jz .L_x86_fatal_bounds\n");
    out.push_str("    dec %ecx\n");
    out.push_str("    mov %ecx, alya_catch_idx\n");
    out.push_str("    mov $alya_str_bounds, %eax\n");
    out.push_str("    mov %eax, alya_err_msg\n");
    out.push_str("    mov $alya_catch_stack_sp, %edx\n");
    out.push_str("    mov (%edx, %ecx, 4), %esp\n");
    out.push_str("    mov $alya_catch_stack_bp, %edx\n");
    out.push_str("    mov (%edx, %ecx, 4), %ebp\n");
    out.push_str("    mov $alya_catch_stack_handler, %edx\n");
    out.push_str("    mov (%edx, %ecx, 4), %eax\n");
    out.push_str("    jmp *%eax\n");
    out.push_str(".L_x86_fatal_bounds:\n");
    out.push_str("    and $-16, %esp\n");
    out.push_str("    push $alya_fmt_bounds\n");
    out.push_str("    call printf\n");
    out.push_str("    push $1\n");
    out.push_str("    call exit\n\n");
}
