pub fn emit_x86_runtime(out: &mut String) {
    // alya_concat
    out.push_str("alya_concat:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    push %ebx\n");
    out.push_str("    mov 8(%ebp), %esi\n");
    out.push_str("    mov 12(%ebp), %edx\n");
    out.push_str("    mov $alya_str_buf, %ecx\n");
    out.push_str("    mov alya_str_idx, %ebx\n");
    out.push_str("    cmp $48000, %ebx\n");
    out.push_str("    jl .L_x86_concat_ok\n");
    out.push_str("    xor %ebx, %ebx\n");
    out.push_str(".L_x86_concat_ok:\n");
    out.push_str("    lea (%ecx, %ebx), %edi\n");
    out.push_str("    mov %edi, %eax\n");
    out.push_str(".L_x86_copy1:\n");
    out.push_str("    movb (%esi), %bl\n");
    out.push_str("    test %bl, %bl\n");
    out.push_str("    jz .L_x86_copy2_start\n");
    out.push_str("    movb %cl, (%edi)\n");
    out.push_str("    inc %esi\n");
    out.push_str("    inc %edi\n");
    out.push_str("    jmp .L_x86_copy1\n");
    out.push_str(".L_x86_copy2_start:\n");
    out.push_str("    mov %edx, %esi\n");
    out.push_str(".L_x86_copy2:\n");
    out.push_str("    movb (%esi), %bl\n");
    out.push_str("    test %bl, %bl\n");
    out.push_str("    jz .L_x86_concat_end\n");
    out.push_str("    movb %cl, (%edi)\n");
    out.push_str("    inc %esi\n");
    out.push_str("    inc %edi\n");
    out.push_str("    jmp .L_x86_copy2\n");
    out.push_str(".L_x86_concat_end:\n");
    out.push_str("    movb $0, (%edi)\n");
    out.push_str("    inc %edi\n");
    out.push_str("    sub %ecx, %edi\n");
    out.push_str("    add $3, %edi\n");
    out.push_str("    and $-4, %edi\n");
    out.push_str("    mov %edi, alya_str_idx\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_len
    out.push_str("fn_len:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    mov 8(%ebp), %edx\n");
    out.push_str("    xor %eax, %eax\n");
    out.push_str(".L_x86_len_loop:\n");
    out.push_str("    cmpb $0, (%edx, %eax)\n");
    out.push_str("    je .L_x86_len_end\n");
    out.push_str("    inc %eax\n");
    out.push_str("    jmp .L_x86_len_loop\n");
    out.push_str(".L_x86_len_end:\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_abs
    out.push_str("fn_abs:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    mov 8(%ebp), %eax\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jns .L_x86_abs_end\n");
    out.push_str("    neg %eax\n");
    out.push_str(".L_x86_abs_end:\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_min
    out.push_str("fn_min:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    mov 8(%ebp), %eax\n");
    out.push_str("    mov 12(%ebp), %edx\n");
    out.push_str("    cmp %edx, %eax\n");
    out.push_str("    jle .L_x86_min_end\n");
    out.push_str("    mov %edx, %eax\n");
    out.push_str(".L_x86_min_end:\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_max
    out.push_str("fn_max:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    mov 8(%ebp), %eax\n");
    out.push_str("    mov 12(%ebp), %edx\n");
    out.push_str("    cmp %edx, %eax\n");
    out.push_str("    jge .L_x86_max_end\n");
    out.push_str("    mov %edx, %eax\n");
    out.push_str(".L_x86_max_end:\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_sqrt
    out.push_str("fn_sqrt:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    mov 8(%ebp), %ecx\n");
    out.push_str("    test %ecx, %ecx\n");
    out.push_str("    jle .L_x86_sqrt_zero\n");
    out.push_str("    cmp $4, %ecx\n");
    out.push_str("    jl .L_x86_sqrt_one\n");
    out.push_str("    push %ebx\n");
    out.push_str("    mov %ecx, %ebx\n");
    out.push_str("    shr $1, %ebx\n");
    out.push_str(".L_x86_sqrt_loop:\n");
    out.push_str("    mov %ecx, %eax\n");
    out.push_str("    xor %edx, %edx\n");
    out.push_str("    div %ebx\n");
    out.push_str("    add %ebx, %eax\n");
    out.push_str("    shr $1, %eax\n");
    out.push_str("    cmp %ebx, %eax\n");
    out.push_str("    jge .L_x86_sqrt_done\n");
    out.push_str("    mov %eax, %ebx\n");
    out.push_str("    jmp .L_x86_sqrt_loop\n");
    out.push_str(".L_x86_sqrt_done:\n");
    out.push_str("    mov %ebx, %eax\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    jmp .L_x86_sqrt_end\n");
    out.push_str(".L_x86_sqrt_one:\n");
    out.push_str("    mov $1, %eax\n");
    out.push_str("    jmp .L_x86_sqrt_end\n");
    out.push_str(".L_x86_sqrt_zero:\n");
    out.push_str("    xor %eax, %eax\n");
    out.push_str(".L_x86_sqrt_end:\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_pow
    out.push_str("fn_pow:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    mov 8(%ebp), %ecx\n");
    out.push_str("    mov 12(%ebp), %edx\n");
    out.push_str("    test %edx, %edx\n");
    out.push_str("    js .L_x86_pow_zero\n");
    out.push_str("    mov $1, %eax\n");
    out.push_str(".L_x86_pow_loop:\n");
    out.push_str("    test %edx, %edx\n");
    out.push_str("    jle .L_x86_pow_end\n");
    out.push_str("    test $1, %edx\n");
    out.push_str("    jz .L_x86_pow_even\n");
    out.push_str("    imul %ecx, %eax\n");
    out.push_str(".L_x86_pow_even:\n");
    out.push_str("    imul %ecx, %ecx\n");
    out.push_str("    shr $1, %edx\n");
    out.push_str("    jmp .L_x86_pow_loop\n");
    out.push_str(".L_x86_pow_zero:\n");
    out.push_str("    xor %eax, %eax\n");
    out.push_str(".L_x86_pow_end:\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_exit
    out.push_str("fn_exit:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push 8(%ebp)\n");
    out.push_str("    call exit\n\n");

    // fn_ask
    out.push_str("fn_ask:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    push %ebx\n");
    out.push_str("    mov 8(%ebp), %eax\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jz .L_x86_ask_read\n");
    out.push_str("    push %eax\n");
    out.push_str("    push $alya_fmt_prompt\n");
    out.push_str("    call printf\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    push $0\n");
    out.push_str("    call fflush\n");
    out.push_str("    add $4, %esp\n");
    out.push_str(".L_x86_ask_read:\n");
    out.push_str("    mov $alya_str_buf, %ecx\n");
    out.push_str("    mov alya_str_idx, %ebx\n");
    out.push_str("    cmp $48000, %ebx\n");
    out.push_str("    jl .L_x86_ask_buf_ok\n");
    out.push_str("    xor %ebx, %ebx\n");
    out.push_str(".L_x86_ask_buf_ok:\n");
    out.push_str("    lea (%ecx, %ebx), %esi\n");
    out.push_str("    mov %esi, %edi\n");
    out.push_str(".L_x86_ask_loop:\n");
    out.push_str("    call getchar\n");
    out.push_str("    cmp $-1, %eax\n");
    out.push_str("    je .L_x86_ask_done\n");
    out.push_str("    cmp $10, %eax\n");
    out.push_str("    je .L_x86_ask_done\n");
    out.push_str("    cmp $13, %eax\n");
    out.push_str("    je .L_x86_ask_loop\n");
    out.push_str("    movb %al, (%edi)\n");
    out.push_str("    inc %edi\n");
    out.push_str("    jmp .L_x86_ask_loop\n");
    out.push_str(".L_x86_ask_done:\n");
    out.push_str("    movb $0, (%edi)\n");
    out.push_str("    inc %edi\n");
    out.push_str("    sub %ecx, %edi\n");
    out.push_str("    add $3, %edi\n");
    out.push_str("    and $-4, %edi\n");
    out.push_str("    mov %edi, alya_str_idx\n");
    out.push_str("    mov %esi, %eax\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_upper
    out.push_str("fn_upper:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov 8(%ebp), %esi\n");
    out.push_str("    mov $alya_str_buf, %ecx\n");
    out.push_str("    mov alya_str_idx, %ebx\n");
    out.push_str("    cmp $48000, %ebx\n");
    out.push_str("    jl .L_x86_upper_buf_ok\n");
    out.push_str("    xor %ebx, %ebx\n");
    out.push_str(".L_x86_upper_buf_ok:\n");
    out.push_str("    lea (%ecx, %ebx), %edi\n");
    out.push_str("    mov %edi, %eax\n");
    out.push_str(".L_x86_upper_loop:\n");
    out.push_str("    movb (%esi), %dl\n");
    out.push_str("    test %dl, %dl\n");
    out.push_str("    jz .L_x86_upper_done\n");
    out.push_str("    cmpb $'a', %dl\n");
    out.push_str("    jl .L_x86_upper_store\n");
    out.push_str("    cmpb $'z', %dl\n");
    out.push_str("    jg .L_x86_upper_store\n");
    out.push_str("    subb $32, %dl\n");
    out.push_str(".L_x86_upper_store:\n");
    out.push_str("    movb %dl, (%edi)\n");
    out.push_str("    inc %esi\n");
    out.push_str("    inc %edi\n");
    out.push_str("    jmp .L_x86_upper_loop\n");
    out.push_str(".L_x86_upper_done:\n");
    out.push_str("    movb $0, (%edi)\n");
    out.push_str("    inc %edi\n");
    out.push_str("    sub %ecx, %edi\n");
    out.push_str("    add $3, %edi\n");
    out.push_str("    and $-4, %edi\n");
    out.push_str("    mov %edi, alya_str_idx\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_lower
    out.push_str("fn_lower:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov 8(%ebp), %esi\n");
    out.push_str("    mov $alya_str_buf, %ecx\n");
    out.push_str("    mov alya_str_idx, %ebx\n");
    out.push_str("    cmp $48000, %ebx\n");
    out.push_str("    jl .L_x86_lower_buf_ok\n");
    out.push_str("    xor %ebx, %ebx\n");
    out.push_str(".L_x86_lower_buf_ok:\n");
    out.push_str("    lea (%ecx, %ebx), %edi\n");
    out.push_str("    mov %edi, %eax\n");
    out.push_str(".L_x86_lower_loop:\n");
    out.push_str("    movb (%esi), %dl\n");
    out.push_str("    test %dl, %dl\n");
    out.push_str("    jz .L_x86_lower_done\n");
    out.push_str("    cmpb $'A', %dl\n");
    out.push_str("    jl .L_x86_lower_store\n");
    out.push_str("    cmpb $'Z', %dl\n");
    out.push_str("    jg .L_x86_lower_store\n");
    out.push_str("    addb $32, %dl\n");
    out.push_str(".L_x86_lower_store:\n");
    out.push_str("    movb %dl, (%edi)\n");
    out.push_str("    inc %esi\n");
    out.push_str("    inc %edi\n");
    out.push_str("    jmp .L_x86_lower_loop\n");
    out.push_str(".L_x86_lower_done:\n");
    out.push_str("    movb $0, (%edi)\n");
    out.push_str("    inc %edi\n");
    out.push_str("    sub %ecx, %edi\n");
    out.push_str("    add $3, %edi\n");
    out.push_str("    and $-4, %edi\n");
    out.push_str("    mov %edi, alya_str_idx\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_trim
    out.push_str("fn_trim:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov 8(%ebp), %esi\n");
    out.push_str(".L_x86_trim_lws:\n");
    out.push_str("    movb (%esi), %al\n");
    out.push_str("    cmpb $32, %al\n");
    out.push_str("    je .L_x86_trim_lws_inc\n");
    out.push_str("    cmpb $9, %al\n");
    out.push_str("    je .L_x86_trim_lws_inc\n");
    out.push_str("    cmpb $10, %al\n");
    out.push_str("    je .L_x86_trim_lws_inc\n");
    out.push_str("    cmpb $13, %al\n");
    out.push_str("    je .L_x86_trim_lws_inc\n");
    out.push_str("    jmp .L_x86_trim_lws_done\n");
    out.push_str(".L_x86_trim_lws_inc:\n");
    out.push_str("    inc %esi\n");
    out.push_str("    jmp .L_x86_trim_lws\n");
    out.push_str(".L_x86_trim_lws_done:\n");
    out.push_str("    mov %esi, %edx\n");
    out.push_str(".L_x86_trim_find_end:\n");
    out.push_str("    cmpb $0, (%edx)\n");
    out.push_str("    je .L_x86_trim_end_found\n");
    out.push_str("    inc %edx\n");
    out.push_str("    jmp .L_x86_trim_find_end\n");
    out.push_str(".L_x86_trim_end_found:\n");
    out.push_str(".L_x86_trim_tws:\n");
    out.push_str("    cmp %esi, %edx\n");
    out.push_str("    jle .L_x86_trim_copy_start\n");
    out.push_str("    movb -1(%edx), %al\n");
    out.push_str("    cmpb $32, %al\n");
    out.push_str("    je .L_x86_trim_tws_dec\n");
    out.push_str("    cmpb $9, %al\n");
    out.push_str("    je .L_x86_trim_tws_dec\n");
    out.push_str("    cmpb $10, %al\n");
    out.push_str("    je .L_x86_trim_tws_dec\n");
    out.push_str("    cmpb $13, %al\n");
    out.push_str("    je .L_x86_trim_tws_dec\n");
    out.push_str("    jmp .L_x86_trim_copy_start\n");
    out.push_str(".L_x86_trim_tws_dec:\n");
    out.push_str("    dec %edx\n");
    out.push_str("    jmp .L_x86_trim_tws\n");
    out.push_str(".L_x86_trim_copy_start:\n");
    out.push_str("    mov $alya_str_buf, %ecx\n");
    out.push_str("    mov alya_str_idx, %ebx\n");
    out.push_str("    cmp $48000, %ebx\n");
    out.push_str("    jl .L_x86_trim_buf_ok\n");
    out.push_str("    xor %ebx, %ebx\n");
    out.push_str(".L_x86_trim_buf_ok:\n");
    out.push_str("    lea (%ecx, %ebx), %edi\n");
    out.push_str("    mov %edi, %eax\n");
    out.push_str(".L_x86_trim_copy_loop:\n");
    out.push_str("    cmp %edx, %esi\n");
    out.push_str("    jge .L_x86_trim_done\n");
    out.push_str("    movb (%esi), %bl\n");
    out.push_str("    movb %bl, (%edi)\n");
    out.push_str("    inc %esi\n");
    out.push_str("    inc %edi\n");
    out.push_str("    jmp .L_x86_trim_copy_loop\n");
    out.push_str(".L_x86_trim_done:\n");
    out.push_str("    movb $0, (%edi)\n");
    out.push_str("    inc %edi\n");
    out.push_str("    sub %ecx, %edi\n");
    out.push_str("    add $3, %edi\n");
    out.push_str("    and $-4, %edi\n");
    out.push_str("    mov %edi, alya_str_idx\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_contains
    out.push_str("fn_contains:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov 8(%ebp), %esi\n");
    out.push_str("    mov 12(%ebp), %edi\n");
    out.push_str("    cmpb $0, (%edi)\n");
    out.push_str("    je .L_x86_contains_match\n");
    out.push_str(".L_x86_contains_outer:\n");
    out.push_str("    cmpb $0, (%esi)\n");
    out.push_str("    je .L_x86_contains_nomatch\n");
    out.push_str("    mov %esi, %eax\n");
    out.push_str("    mov %edi, %edx\n");
    out.push_str(".L_x86_contains_inner:\n");
    out.push_str("    movb (%edx), %cl\n");
    out.push_str("    test %cl, %cl\n");
    out.push_str("    jz .L_x86_contains_match\n");
    out.push_str("    movb (%eax), %bl\n");
    out.push_str("    cmp %bl, %cl\n");
    out.push_str("    jne .L_x86_contains_next\n");
    out.push_str("    inc %eax\n");
    out.push_str("    inc %edx\n");
    out.push_str("    jmp .L_x86_contains_inner\n");
    out.push_str(".L_x86_contains_next:\n");
    out.push_str("    inc %esi\n");
    out.push_str("    jmp .L_x86_contains_outer\n");
    out.push_str(".L_x86_contains_match:\n");
    out.push_str("    mov $1, %eax\n");
    out.push_str("    jmp .L_x86_contains_end\n");
    out.push_str(".L_x86_contains_nomatch:\n");
    out.push_str("    xor %eax, %eax\n");
    out.push_str(".L_x86_contains_end:\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_substring / fn_substr
    out.push_str("fn_substr:\n");
    out.push_str("fn_substring:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov 8(%ebp), %esi\n");
    out.push_str("    mov 12(%ebp), %edx\n");
    out.push_str("    mov 16(%ebp), %ebx\n");
    out.push_str("    cmp $0, %edx\n");
    out.push_str("    jge .L_x86_sub_adv\n");
    out.push_str("    xor %edx, %edx\n");
    out.push_str(".L_x86_sub_adv:\n");
    out.push_str("    test %edx, %edx\n");
    out.push_str("    jle .L_x86_sub_adv_done\n");
    out.push_str("    cmpb $0, (%esi)\n");
    out.push_str("    je .L_x86_sub_adv_done\n");
    out.push_str("    inc %esi\n");
    out.push_str("    dec %edx\n");
    out.push_str("    jmp .L_x86_sub_adv\n");
    out.push_str(".L_x86_sub_adv_done:\n");
    out.push_str("    mov $alya_str_buf, %ecx\n");
    out.push_str("    mov alya_str_idx, %edx\n");
    out.push_str("    cmp $48000, %edx\n");
    out.push_str("    jl .L_x86_sub_buf_ok\n");
    out.push_str("    xor %edx, %edx\n");
    out.push_str(".L_x86_sub_buf_ok:\n");
    out.push_str("    lea (%ecx, %edx), %edi\n");
    out.push_str("    mov %edi, %eax\n");
    out.push_str(".L_x86_sub_copy:\n");
    out.push_str("    cmpb $0, (%esi)\n");
    out.push_str("    je .L_x86_sub_done\n");
    out.push_str("    test %ebx, %ebx\n");
    out.push_str("    jz .L_x86_sub_done\n");
    out.push_str("    movb (%esi), %dl\n");
    out.push_str("    movb %dl, (%edi)\n");
    out.push_str("    inc %esi\n");
    out.push_str("    inc %edi\n");
    out.push_str("    cmp $0, %ebx\n");
    out.push_str("    jl .L_x86_sub_copy\n");
    out.push_str("    dec %ebx\n");
    out.push_str("    jmp .L_x86_sub_copy\n");
    out.push_str(".L_x86_sub_done:\n");
    out.push_str("    movb $0, (%edi)\n");
    out.push_str("    inc %edi\n");
    out.push_str("    sub %ecx, %edi\n");
    out.push_str("    add $3, %edi\n");
    out.push_str("    and $-4, %edi\n");
    out.push_str("    mov %edi, alya_str_idx\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_char_at
    out.push_str("fn_char_at:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov 8(%ebp), %esi\n");
    out.push_str("    mov 12(%ebp), %edx\n");
    out.push_str("    mov $alya_str_empty, %eax\n");
    out.push_str("    test %esi, %esi\n");
    out.push_str("    jz .L_x86_char_at_end\n");
    out.push_str("    cmp $0, %edx\n");
    out.push_str("    jl .L_x86_char_at_end\n");
    out.push_str(".L_x86_char_at_adv:\n");
    out.push_str("    test %edx, %edx\n");
    out.push_str("    jle .L_x86_char_at_fetch\n");
    out.push_str("    cmpb $0, (%esi)\n");
    out.push_str("    je .L_x86_char_at_end\n");
    out.push_str("    inc %esi\n");
    out.push_str("    dec %edx\n");
    out.push_str("    jmp .L_x86_char_at_adv\n");
    out.push_str(".L_x86_char_at_fetch:\n");
    out.push_str("    movzbl (%esi), %edx\n");
    out.push_str("    test %edx, %edx\n");
    out.push_str("    jz .L_x86_char_at_end\n");
    out.push_str("    mov $alya_str_buf, %ecx\n");
    out.push_str("    mov alya_str_idx, %ebx\n");
    out.push_str("    cmp $48000, %ebx\n");
    out.push_str("    jl .L_x86_char_at_buf_ok\n");
    out.push_str("    xor %ebx, %ebx\n");
    out.push_str(".L_x86_char_at_buf_ok:\n");
    out.push_str("    lea (%ecx, %ebx), %edi\n");
    out.push_str("    mov %edi, %eax\n");
    out.push_str("    movb %dl, (%edi)\n");
    out.push_str("    movb $0, 1(%edi)\n");
    out.push_str("    add $2, %edi\n");
    out.push_str("    sub %ecx, %edi\n");
    out.push_str("    add $3, %edi\n");
    out.push_str("    and $-4, %edi\n");
    out.push_str("    mov %edi, alya_str_idx\n");
    out.push_str(".L_x86_char_at_end:\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_ord / fn_char_code
    out.push_str("fn_char_code:\n");
    out.push_str("fn_ord:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    mov 8(%ebp), %eax\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jz .L_x86_ord_zero\n");
    out.push_str("    cmp $256, %eax\n");
    out.push_str("    jb .L_x86_ord_ret\n");
    out.push_str("    movzbl (%eax), %eax\n");
    out.push_str("    jmp .L_x86_ord_ret\n");
    out.push_str(".L_x86_ord_zero:\n");
    out.push_str("    xor %eax, %eax\n");
    out.push_str(".L_x86_ord_ret:\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_chr / fn_char_from_code
    out.push_str("fn_char_from_code:\n");
    out.push_str("fn_chr:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov 8(%ebp), %edx\n");
    out.push_str("    mov $alya_str_empty, %eax\n");
    out.push_str("    test %edx, %edx\n");
    out.push_str("    jz .L_x86_chr_end\n");
    out.push_str("    cmp $256, %edx\n");
    out.push_str("    jb .L_x86_chr_code\n");
    out.push_str("    movzbl (%edx), %edx\n");
    out.push_str(".L_x86_chr_code:\n");
    out.push_str("    and $255, %edx\n");
    out.push_str("    jz .L_x86_chr_end\n");
    out.push_str("    mov $alya_str_buf, %ecx\n");
    out.push_str("    mov alya_str_idx, %ebx\n");
    out.push_str("    cmp $48000, %ebx\n");
    out.push_str("    jl .L_x86_chr_buf_ok\n");
    out.push_str("    xor %ebx, %ebx\n");
    out.push_str(".L_x86_chr_buf_ok:\n");
    out.push_str("    lea (%ecx, %ebx), %edi\n");
    out.push_str("    mov %edi, %eax\n");
    out.push_str("    movb %dl, (%edi)\n");
    out.push_str("    movb $0, 1(%edi)\n");
    out.push_str("    add $2, %edi\n");
    out.push_str("    sub %ecx, %edi\n");
    out.push_str("    add $3, %edi\n");
    out.push_str("    and $-4, %edi\n");
    out.push_str("    mov %edi, alya_str_idx\n");
    out.push_str(".L_x86_chr_end:\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_str
    out.push_str(".global fn_str\n");
    out.push_str("fn_str:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %edi\n");
    out.push_str("    push %esi\n");
    out.push_str("    mov 8(%ebp), %eax\n");
    out.push_str("    mov $alya_str_buf, %ecx\n");
    out.push_str("    mov alya_str_idx, %ebx\n");
    out.push_str("    cmp $48000, %ebx\n");
    out.push_str("    jl .L_x86_str_buf_ok\n");
    out.push_str("    xor %ebx, %ebx\n");
    out.push_str(".L_x86_str_buf_ok:\n");
    out.push_str("    lea (%ecx, %ebx), %edi\n");
    out.push_str("    mov %edi, %esi\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jnz .L_x86_str_chk_neg\n");
    out.push_str("    movb $'0', (%edi)\n");
    out.push_str("    movb $0, 1(%edi)\n");
    out.push_str("    add $2, %edi\n");
    out.push_str("    jmp .L_x86_str_finish\n");
    out.push_str(".L_x86_str_chk_neg:\n");
    out.push_str("    jns .L_x86_str_pos\n");
    out.push_str("    movb $'-', (%edi)\n");
    out.push_str("    inc %edi\n");
    out.push_str("    neg %eax\n");
    out.push_str(".L_x86_str_pos:\n");
    out.push_str("    xor %ecx, %ecx\n");
    out.push_str("    mov $10, %ebx\n");
    out.push_str(".L_x86_str_div_loop:\n");
    out.push_str("    xor %edx, %edx\n");
    out.push_str("    div %ebx\n");
    out.push_str("    add $'0', %dl\n");
    out.push_str("    push %edx\n");
    out.push_str("    inc %ecx\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jnz .L_x86_str_div_loop\n");
    out.push_str(".L_x86_str_copy_loop:\n");
    out.push_str("    pop %edx\n");
    out.push_str("    movb %dl, (%edi)\n");
    out.push_str("    inc %edi\n");
    out.push_str("    dec %ecx\n");
    out.push_str("    jnz .L_x86_str_copy_loop\n");
    out.push_str("    movb $0, (%edi)\n");
    out.push_str("    inc %edi\n");
    out.push_str(".L_x86_str_finish:\n");
    out.push_str("    mov $alya_str_buf, %ecx\n");
    out.push_str("    sub %ecx, %edi\n");
    out.push_str("    add $3, %edi\n");
    out.push_str("    and $-4, %edi\n");
    out.push_str("    mov %edi, alya_str_idx\n");
    out.push_str("    mov %esi, %eax\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_is_digit
    out.push_str("fn_is_digit:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    mov 8(%ebp), %edx\n");
    out.push_str("    xor %eax, %eax\n");
    out.push_str("    test %edx, %edx\n");
    out.push_str("    jz .L_x86_is_digit_end\n");
    out.push_str("    cmp $256, %edx\n");
    out.push_str("    jb .L_x86_is_digit_cmp\n");
    out.push_str("    movzbl (%edx), %edx\n");
    out.push_str(".L_x86_is_digit_cmp:\n");
    out.push_str("    cmp $'0', %edx\n");
    out.push_str("    jb .L_x86_is_digit_end\n");
    out.push_str("    cmp $'9', %edx\n");
    out.push_str("    ja .L_x86_is_digit_end\n");
    out.push_str("    mov $1, %eax\n");
    out.push_str(".L_x86_is_digit_end:\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_is_alpha
    out.push_str("fn_is_alpha:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    mov 8(%ebp), %edx\n");
    out.push_str("    xor %eax, %eax\n");
    out.push_str("    test %edx, %edx\n");
    out.push_str("    jz .L_x86_is_alpha_end\n");
    out.push_str("    cmp $256, %edx\n");
    out.push_str("    jb .L_x86_is_alpha_cmp\n");
    out.push_str("    movzbl (%edx), %edx\n");
    out.push_str(".L_x86_is_alpha_cmp:\n");
    out.push_str("    cmp $'_', %edx\n");
    out.push_str("    je .L_x86_is_alpha_true\n");
    out.push_str("    cmp $'a', %edx\n");
    out.push_str("    jb .L_x86_is_alpha_upper\n");
    out.push_str("    cmp $'z', %edx\n");
    out.push_str("    jbe .L_x86_is_alpha_true\n");
    out.push_str(".L_x86_is_alpha_upper:\n");
    out.push_str("    cmp $'A', %edx\n");
    out.push_str("    jb .L_x86_is_alpha_end\n");
    out.push_str("    cmp $'Z', %edx\n");
    out.push_str("    jbe .L_x86_is_alpha_true\n");
    out.push_str("    jmp .L_x86_is_alpha_end\n");
    out.push_str(".L_x86_is_alpha_true:\n");
    out.push_str("    mov $1, %eax\n");
    out.push_str(".L_x86_is_alpha_end:\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_is_alnum
    out.push_str("fn_is_alnum:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push 8(%ebp)\n");
    out.push_str("    call fn_is_alpha\n");
    out.push_str("    add $4, %esp\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jnz .L_x86_is_alnum_end\n");
    out.push_str("    push 8(%ebp)\n");
    out.push_str("    call fn_is_digit\n");
    out.push_str("    add $4, %esp\n");
    out.push_str(".L_x86_is_alnum_end:\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_is_space / fn_is_whitespace
    out.push_str("fn_is_whitespace:\n");
    out.push_str("fn_is_space:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    mov 8(%ebp), %edx\n");
    out.push_str("    xor %eax, %eax\n");
    out.push_str("    test %edx, %edx\n");
    out.push_str("    jz .L_x86_is_space_end\n");
    out.push_str("    cmp $256, %edx\n");
    out.push_str("    jb .L_x86_is_space_cmp\n");
    out.push_str("    movzbl (%edx), %edx\n");
    out.push_str(".L_x86_is_space_cmp:\n");
    out.push_str("    cmp $' ', %edx\n");
    out.push_str("    je .L_x86_is_space_true\n");
    out.push_str("    cmp $'\\t', %edx\n");
    out.push_str("    je .L_x86_is_space_true\n");
    out.push_str("    cmp $'\\n', %edx\n");
    out.push_str("    je .L_x86_is_space_true\n");
    out.push_str("    cmp $'\\r', %edx\n");
    out.push_str("    je .L_x86_is_space_true\n");
    out.push_str("    jmp .L_x86_is_space_end\n");
    out.push_str(".L_x86_is_space_true:\n");
    out.push_str("    mov $1, %eax\n");
    out.push_str(".L_x86_is_space_end:\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_file_exists
    out.push_str("fn_file_exists:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    mov 8(%ebp), %eax\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jz .L_x86_fexists_no\n");
    out.push_str("    push $alya_str_mode_rb\n");
    out.push_str("    push 8(%ebp)\n");
    out.push_str("    call fopen\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jz .L_x86_fexists_no\n");
    out.push_str("    push %eax\n");
    out.push_str("    call fclose\n");
    out.push_str("    add $4, %esp\n");
    out.push_str("    mov $1, %eax\n");
    out.push_str("    jmp .L_x86_fexists_end\n");
    out.push_str(".L_x86_fexists_no:\n");
    out.push_str("    xor %eax, %eax\n");
    out.push_str(".L_x86_fexists_end:\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_delete_file / fn_remove_file
    out.push_str(".global fn_delete_file\n");
    out.push_str("fn_delete_file:\n");
    out.push_str(".global fn_remove_file\n");
    out.push_str("fn_remove_file:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    mov 8(%ebp), %eax\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jz .L_x86_fdel_fail\n");
    out.push_str("    push 8(%ebp)\n");
    out.push_str("    call remove\n");
    out.push_str("    add $4, %esp\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jnz .L_x86_fdel_fail\n");
    out.push_str("    mov $1, %eax\n");
    out.push_str("    jmp .L_x86_fdel_end\n");
    out.push_str(".L_x86_fdel_fail:\n");
    out.push_str("    xor %eax, %eax\n");
    out.push_str(".L_x86_fdel_end:\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_write_file
    out.push_str("fn_write_file:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov 8(%ebp), %eax\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jz .L_x86_fwrite_fail\n");
    out.push_str("    push $alya_str_mode_wb\n");
    out.push_str("    push 8(%ebp)\n");
    out.push_str("    call fopen\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jz .L_x86_fwrite_fail\n");
    out.push_str("    mov %eax, %ebx\n");
    out.push_str("    mov 12(%ebp), %esi\n");
    out.push_str("    xor %edi, %edi\n");
    out.push_str("    test %esi, %esi\n");
    out.push_str("    jz .L_x86_fwrite_write\n");
    out.push_str(".L_x86_fwrite_len_loop:\n");
    out.push_str("    cmpb $0, (%esi, %edi)\n");
    out.push_str("    je .L_x86_fwrite_write\n");
    out.push_str("    inc %edi\n");
    out.push_str("    jmp .L_x86_fwrite_len_loop\n");
    out.push_str(".L_x86_fwrite_write:\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %edi\n");
    out.push_str("    push $1\n");
    out.push_str("    push %esi\n");
    out.push_str("    call fwrite\n");
    out.push_str("    add $16, %esp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    call fclose\n");
    out.push_str("    add $4, %esp\n");
    out.push_str("    mov $1, %eax\n");
    out.push_str("    jmp .L_x86_fwrite_end\n");
    out.push_str(".L_x86_fwrite_fail:\n");
    out.push_str("    xor %eax, %eax\n");
    out.push_str(".L_x86_fwrite_end:\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_read_file
    out.push_str("fn_read_file:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov 8(%ebp), %eax\n");
    out.push_str("    mov $alya_str_empty, %edi\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jz .L_x86_fread_ret\n");
    out.push_str("    push $alya_str_mode_rb\n");
    out.push_str("    push 8(%ebp)\n");
    out.push_str("    call fopen\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jz .L_x86_fread_ret\n");
    out.push_str("    mov %eax, %ebx\n");
    out.push_str("    push $2\n");
    out.push_str("    push $0\n");
    out.push_str("    push %ebx\n");
    out.push_str("    call fseek\n");
    out.push_str("    add $12, %esp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    call ftell\n");
    out.push_str("    add $4, %esp\n");
    out.push_str("    cmp $0, %eax\n");
    out.push_str("    jl .L_x86_fread_close\n");
    out.push_str("    mov %eax, %esi\n");
    out.push_str("    push $0\n");
    out.push_str("    push $0\n");
    out.push_str("    push %ebx\n");
    out.push_str("    call fseek\n");
    out.push_str("    add $12, %esp\n");
    out.push_str("    lea 1(%esi), %edx\n");
    out.push_str("    push %edx\n");
    out.push_str("    push $1\n");
    out.push_str("    call calloc\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    mov %eax, %edi\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push $1\n");
    out.push_str("    push %edi\n");
    out.push_str("    call fread\n");
    out.push_str("    add $16, %esp\n");
    out.push_str("    movb $0, (%edi, %esi)\n");
    out.push_str(".L_x86_fread_close:\n");
    out.push_str("    push %ebx\n");
    out.push_str("    call fclose\n");
    out.push_str("    add $4, %esp\n");
    out.push_str(".L_x86_fread_ret:\n");
    out.push_str("    mov %edi, %eax\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // alya_error_div_zero
    out.push_str("alya_error_div_zero:\n");
    out.push_str("    mov alya_catch_idx, %ecx\n");
    out.push_str("    test %ecx, %ecx\n");
    out.push_str("    jz .L_x86_fatal_div_zero\n");
    out.push_str("    dec %ecx\n");
    out.push_str("    mov %ecx, alya_catch_idx\n");
    out.push_str("    mov $alya_str_div_zero, %eax\n");
    out.push_str("    mov %eax, alya_err_msg\n");
    out.push_str("    mov $alya_catch_stack_sp, %edx\n");
    out.push_str("    mov (%edx, %ecx, 4), %esp\n");
    out.push_str("    mov $alya_catch_stack_bp, %edx\n");
    out.push_str("    mov (%edx, %ecx, 4), %ebp\n");
    out.push_str("    mov $alya_catch_stack_handler, %edx\n");
    out.push_str("    mov (%edx, %ecx, 4), %eax\n");
    out.push_str("    jmp *%eax\n");
    out.push_str(".L_x86_fatal_div_zero:\n");
    out.push_str("    and $-16, %esp\n");
    out.push_str("    push $alya_fmt_div_zero\n");
    out.push_str("    call printf\n");
    out.push_str("    push $1\n");
    out.push_str("    call exit\n\n");

    // alya_array_new
    out.push_str("alya_array_new:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov 8(%ebp), %esi\n");
    out.push_str("    mov %esi, %ebx\n");
    out.push_str("    cmp $8, %ebx\n");
    out.push_str("    jge .L_x86_new_cap_ok\n");
    out.push_str("    mov $8, %ebx\n");
    out.push_str("    jmp .L_x86_new_alloc_hdr\n");
    out.push_str(".L_x86_new_cap_ok:\n");
    out.push_str("    shl $1, %ebx\n");
    out.push_str(".L_x86_new_alloc_hdr:\n");
    out.push_str("    push $12\n");
    out.push_str("    push $1\n");
    out.push_str("    call calloc\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    mov %eax, %edi\n");
    out.push_str("    push $4\n");
    out.push_str("    push %ebx\n");
    out.push_str("    call calloc\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    mov %esi, (%edi)\n");
    out.push_str("    mov %ebx, 4(%edi)\n");
    out.push_str("    mov %eax, 8(%edi)\n");
    out.push_str("    mov %edi, %eax\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // alya_array_push
    out.push_str("alya_array_push:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov 8(%ebp), %esi\n");
    out.push_str("    mov 12(%ebp), %edi\n");
    out.push_str("    mov (%esi), %eax\n");
    out.push_str("    mov 4(%esi), %ebx\n");
    out.push_str("    cmp %ebx, %eax\n");
    out.push_str("    jl .L_x86_push_store\n");
    out.push_str("    test %ebx, %ebx\n");
    out.push_str("    jnz .L_x86_push_double\n");
    out.push_str("    mov $8, %ebx\n");
    out.push_str("    jmp .L_x86_push_realloc\n");
    out.push_str(".L_x86_push_double:\n");
    out.push_str("    shl $1, %ebx\n");
    out.push_str(".L_x86_push_realloc:\n");
    out.push_str("    mov %ebx, 4(%esi)\n");
    out.push_str("    lea (, %ebx, 4), %eax\n");
    out.push_str("    push %eax\n");
    out.push_str("    push 8(%esi)\n");
    out.push_str("    call realloc\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    mov %eax, 8(%esi)\n");
    out.push_str(".L_x86_push_store:\n");
    out.push_str("    mov 8(%esi), %edx\n");
    out.push_str("    mov (%esi), %eax\n");
    out.push_str("    mov %edi, (%edx, %eax, 4)\n");
    out.push_str("    inc %eax\n");
    out.push_str("    mov %eax, (%esi)\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // alya_array_pop
    out.push_str("alya_array_pop:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %ebx\n");
    out.push_str("    mov 8(%ebp), %esi\n");
    out.push_str("    mov (%esi), %eax\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jle alya_error_index_out_of_bounds\n");
    out.push_str("    dec %eax\n");
    out.push_str("    mov %eax, (%esi)\n");
    out.push_str("    mov 8(%esi), %edx\n");
    out.push_str("    mov (%edx, %eax, 4), %eax\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    pop %esi\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // alya_print_array
    out.push_str("alya_print_array:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov 8(%ebp), %esi\n");
    out.push_str("    test %esi, %esi\n");
    out.push_str("    jnz .L_x86_arr_not_null\n");
    out.push_str("    push $alya_fmt_arr_empty\n");
    out.push_str("    call printf\n");
    out.push_str("    add $4, %esp\n");
    out.push_str("    jmp .L_x86_arr_exit\n");
    out.push_str(".L_x86_arr_not_null:\n");
    out.push_str("    mov (%esi), %edi\n");
    out.push_str("    push $alya_fmt_arr_open\n");
    out.push_str("    call printf\n");
    out.push_str("    add $4, %esp\n");
    out.push_str("    xor %ebx, %ebx\n");
    out.push_str(".L_x86_arr_loop:\n");
    out.push_str("    cmp %edi, %ebx\n");
    out.push_str("    jge .L_x86_arr_close_call\n");
    out.push_str("    test %ebx, %ebx\n");
    out.push_str("    jz .L_x86_arr_print_elem\n");
    out.push_str("    push $alya_fmt_arr_comma\n");
    out.push_str("    call printf\n");
    out.push_str("    add $4, %esp\n");
    out.push_str(".L_x86_arr_print_elem:\n");
    out.push_str("    mov 8(%esi), %edx\n");
    out.push_str("    push (%edx, %ebx, 4)\n");
    out.push_str("    push $alya_fmt_arr_elem\n");
    out.push_str("    call printf\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    inc %ebx\n");
    out.push_str("    jmp .L_x86_arr_loop\n");
    out.push_str(".L_x86_arr_close_call:\n");
    out.push_str("    push $alya_fmt_arr_close\n");
    out.push_str("    call printf\n");
    out.push_str("    add $4, %esp\n");
    out.push_str(".L_x86_arr_exit:\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // alya_struct_new
    out.push_str("alya_struct_new:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    mov 8(%ebp), %esi\n");
    out.push_str("    mov 12(%ebp), %ebx\n");
    out.push_str("    lea 1(%ebx), %eax\n");
    out.push_str("    push $4\n");
    out.push_str("    push %eax\n");
    out.push_str("    call calloc\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    mov %esi, (%eax)\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // alya_print_struct
    out.push_str("alya_print_struct:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov 8(%ebp), %esi\n");
    out.push_str("    test %esi, %esi\n");
    out.push_str("    jnz .L_x86_struct_not_null\n");
    out.push_str("    push $alya_fmt_struct_null\n");
    out.push_str("    call printf\n");
    out.push_str("    add $4, %esp\n");
    out.push_str("    jmp .L_x86_struct_exit\n");
    out.push_str(".L_x86_struct_not_null:\n");
    out.push_str("    mov (%esi), %edi\n");
    out.push_str("    push (%edi)\n");
    out.push_str("    push $alya_fmt_struct_open\n");
    out.push_str("    call printf\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    xor %ebx, %ebx\n");
    out.push_str(".L_x86_struct_loop:\n");
    out.push_str("    cmp 4(%edi), %ebx\n");
    out.push_str("    jge .L_x86_struct_close\n");
    out.push_str("    test %ebx, %ebx\n");
    out.push_str("    jz .L_x86_struct_print_f\n");
    out.push_str("    push $alya_fmt_struct_comma\n");
    out.push_str("    call printf\n");
    out.push_str("    add $4, %esp\n");
    out.push_str(".L_x86_struct_print_f:\n");
    out.push_str("    push 4(%esi, %ebx, 4)\n");
    out.push_str("    push 8(%edi, %ebx, 4)\n");
    out.push_str("    push $alya_fmt_struct_field\n");
    out.push_str("    call printf\n");
    out.push_str("    add $12, %esp\n");
    out.push_str("    inc %ebx\n");
    out.push_str("    jmp .L_x86_struct_loop\n");
    out.push_str(".L_x86_struct_close:\n");
    out.push_str("    push $alya_fmt_struct_close\n");
    out.push_str("    call printf\n");
    out.push_str("    add $4, %esp\n");
    out.push_str(".L_x86_struct_exit:\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // alya_error_index_out_of_bounds
    out.push_str("alya_error_index_out_of_bounds:\n");
    out.push_str("    mov alya_catch_idx, %ecx\n");
    out.push_str("    test %ecx, %ecx\n");
    out.push_str("    jz .L_x86_fatal_bounds\n");
    out.push_str("    dec %ecx\n");
    out.push_str("    mov %ecx, alya_catch_idx\n");
    out.push_str("    mov $alya_str_bounds, %eax\n");
    out.push_str("    mov %eax, alya_err_msg\n");
    out.push_str("    mov $alya_catch_stack_sp, %edx\n");
    out.push_str("    mov (%edx, %ecx, 4), %esp\n");
    out.push_str("    mov $alya_catch_stack_bp, %edx\n");
    out.push_str("    mov (%edx, %ecx, 4), %ebp\n");
    out.push_str("    mov $alya_catch_stack_handler, %edx\n");
    out.push_str("    mov (%edx, %ecx, 4), %eax\n");
    out.push_str("    jmp *%eax\n");
    out.push_str(".L_x86_fatal_bounds:\n");
    out.push_str("    and $-16, %esp\n");
    out.push_str("    push $alya_fmt_bounds\n");
    out.push_str("    call printf\n");
    out.push_str("    push $1\n");
    out.push_str("    call exit\n\n");

    // fn_args
    out.push_str(".global fn_args\n");
    out.push_str("fn_args:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov alya_argc, %eax\n");
    out.push_str("    cmp $1, %eax\n");
    out.push_str("    jg .L_x86_args_has_items\n");
    out.push_str("    push $0\n");
    out.push_str("    call alya_array_new\n");
    out.push_str("    add $4, %esp\n");
    out.push_str("    jmp .L_x86_args_ret\n");
    out.push_str(".L_x86_args_has_items:\n");
    out.push_str("    dec %eax\n");
    out.push_str("    mov %eax, %esi\n");
    out.push_str("    push %esi\n");
    out.push_str("    call alya_array_new\n");
    out.push_str("    add $4, %esp\n");
    out.push_str("    mov %eax, %edi\n");
    out.push_str("    mov alya_argv, %edx\n");
    out.push_str("    xor %ecx, %ecx\n");
    out.push_str(".L_x86_args_loop:\n");
    out.push_str("    cmp %esi, %ecx\n");
    out.push_str("    jge .L_x86_args_done\n");
    out.push_str("    mov 4(%edx, %ecx, 4), %eax\n");
    out.push_str("    mov 8(%edi), %ebx\n");
    out.push_str("    mov %eax, (%ebx, %ecx, 4)\n");
    out.push_str("    inc %ecx\n");
    out.push_str("    jmp .L_x86_args_loop\n");
    out.push_str(".L_x86_args_done:\n");
    out.push_str("    mov %edi, %eax\n");
    out.push_str(".L_x86_args_ret:\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_join
    out.push_str(".global fn_join\n");
    out.push_str("fn_join:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    sub $16, %esp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov 8(%ebp), %eax\n");
    out.push_str("    mov %eax, -8(%ebp)\n"); // arr
    out.push_str("    mov 12(%ebp), %eax\n");
    out.push_str("    mov %eax, -12(%ebp)\n"); // delim
    out.push_str("    mov -8(%ebp), %esi\n");
    out.push_str("    test %esi, %esi\n");
    out.push_str("    jz .L_x86_join_empty\n");
    out.push_str("    mov (%esi), %eax\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jz .L_x86_join_empty\n");
    out.push_str("    mov $alya_str_buf, %ecx\n");
    out.push_str("    mov alya_str_idx, %ebx\n");
    out.push_str("    cmp $48000, %ebx\n");
    out.push_str("    jl .L_x86_join_buf_ok\n");
    out.push_str("    xor %ebx, %ebx\n");
    out.push_str(".L_x86_join_buf_ok:\n");
    out.push_str("    lea (%ecx, %ebx), %edi\n");
    out.push_str("    mov %edi, -4(%ebp)\n"); // start_ptr
    out.push_str("    movl $0, -16(%ebp)\n"); // i = 0
    out.push_str(".L_x86_join_loop:\n");
    out.push_str("    mov -8(%ebp), %esi\n");
    out.push_str("    mov -16(%ebp), %eax\n");
    out.push_str("    cmp (%esi), %eax\n");
    out.push_str("    jge .L_x86_join_finish\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jz .L_x86_join_copy_elem\n");
    out.push_str("    mov -12(%ebp), %esi\n"); // copy delim
    out.push_str(".L_x86_join_copy_delim:\n");
    out.push_str("    movb (%esi), %al\n");
    out.push_str("    test %al, %al\n");
    out.push_str("    jz .L_x86_join_copy_elem\n");
    out.push_str("    movb %al, (%edi)\n");
    out.push_str("    inc %esi\n");
    out.push_str("    inc %edi\n");
    out.push_str("    jmp .L_x86_join_copy_delim\n");
    out.push_str(".L_x86_join_copy_elem:\n");
    out.push_str("    mov -8(%ebp), %esi\n");
    out.push_str("    mov 8(%esi), %esi\n");
    out.push_str("    mov -16(%ebp), %eax\n");
    out.push_str("    mov (%esi, %eax, 4), %esi\n");
    out.push_str(".L_x86_join_copy_elem_loop:\n");
    out.push_str("    movb (%esi), %al\n");
    out.push_str("    test %al, %al\n");
    out.push_str("    jz .L_x86_join_elem_done\n");
    out.push_str("    movb %al, (%edi)\n");
    out.push_str("    inc %esi\n");
    out.push_str("    inc %edi\n");
    out.push_str("    jmp .L_x86_join_copy_elem_loop\n");
    out.push_str(".L_x86_join_elem_done:\n");
    out.push_str("    incl -16(%ebp)\n");
    out.push_str("    jmp .L_x86_join_loop\n");
    out.push_str(".L_x86_join_finish:\n");
    out.push_str("    movb $0, (%edi)\n");
    out.push_str("    inc %edi\n");
    out.push_str("    mov $alya_str_buf, %ecx\n");
    out.push_str("    sub %ecx, %edi\n");
    out.push_str("    add $3, %edi\n");
    out.push_str("    and $-4, %edi\n");
    out.push_str("    mov %edi, alya_str_idx\n");
    out.push_str("    mov -4(%ebp), %eax\n");
    out.push_str("    jmp .L_x86_join_ret\n");
    out.push_str(".L_x86_join_empty:\n");
    out.push_str("    mov $alya_str_empty, %eax\n");
    out.push_str(".L_x86_join_ret:\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_split
    out.push_str(".global fn_split\n");
    out.push_str("fn_split:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    sub $32, %esp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov 8(%ebp), %eax\n");
    out.push_str("    mov %eax, -4(%ebp)\n"); // str
    out.push_str("    mov 12(%ebp), %eax\n");
    out.push_str("    mov %eax, -8(%ebp)\n"); // delim
    out.push_str("    push $0\n");
    out.push_str("    call alya_array_new\n");
    out.push_str("    add $4, %esp\n");
    out.push_str("    mov %eax, -12(%ebp)\n"); // arr
    out.push_str("    mov -8(%ebp), %esi\n");
    out.push_str("    xor %ecx, %ecx\n");
    out.push_str(".L_x86_split_dlen_loop:\n");
    out.push_str("    cmpb $0, (%esi, %ecx)\n");
    out.push_str("    je .L_x86_split_dlen_done\n");
    out.push_str("    inc %ecx\n");
    out.push_str("    jmp .L_x86_split_dlen_loop\n");
    out.push_str(".L_x86_split_dlen_done:\n");
    out.push_str("    mov %ecx, -16(%ebp)\n"); // delim_len
    out.push_str("    test %ecx, %ecx\n");
    out.push_str("    jnz .L_x86_split_non_empty_delim\n");
    out.push_str("    mov -4(%ebp), %esi\n"); // empty delim
    out.push_str(".L_x86_split_empty_loop:\n");
    out.push_str("    movb (%esi), %al\n");
    out.push_str("    test %al, %al\n");
    out.push_str("    jz .L_x86_split_ret\n");
    out.push_str("    mov $alya_str_buf, %ecx\n");
    out.push_str("    mov alya_str_idx, %ebx\n");
    out.push_str("    cmp $48000, %ebx\n");
    out.push_str("    jl .L_x86_se1\n");
    out.push_str("    xor %ebx, %ebx\n");
    out.push_str(".L_x86_se1:\n");
    out.push_str("    lea (%ecx, %ebx), %edi\n");
    out.push_str("    mov %edi, %edx\n");
    out.push_str("    movb %al, (%edi)\n");
    out.push_str("    movb $0, 1(%edi)\n");
    out.push_str("    add $2, %edi\n");
    out.push_str("    sub %ecx, %edi\n");
    out.push_str("    add $3, %edi\n");
    out.push_str("    and $-4, %edi\n");
    out.push_str("    mov %edi, alya_str_idx\n");
    out.push_str("    push %edx\n");
    out.push_str("    push -12(%ebp)\n");
    out.push_str("    call alya_array_push\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    inc %esi\n");
    out.push_str("    jmp .L_x86_split_empty_loop\n");
    out.push_str(".L_x86_split_non_empty_delim:\n");
    out.push_str("    mov -4(%ebp), %eax\n");
    out.push_str("    mov %eax, -20(%ebp)\n"); // curr
    out.push_str("    mov %eax, -24(%ebp)\n"); // token_start
    out.push_str(".L_x86_split_main_loop:\n");
    out.push_str("    mov -20(%ebp), %esi\n");
    out.push_str("    cmpb $0, (%esi)\n");
    out.push_str("    je .L_x86_split_emit_final\n");
    out.push_str("    mov -16(%ebp), %ecx\n"); // delim_len
    out.push_str("    mov -8(%ebp), %edx\n"); // delim
    out.push_str("    xor %ebx, %ebx\n"); // k = 0
    out.push_str(".L_x86_split_cmp_loop:\n");
    out.push_str("    cmp %ecx, %ebx\n");
    out.push_str("    jge .L_x86_split_matched\n");
    out.push_str("    movb (%edx, %ebx), %al\n");
    out.push_str("    cmpb %al, (%esi, %ebx)\n");
    out.push_str("    jne .L_x86_split_cmp_fail\n");
    out.push_str("    inc %ebx\n");
    out.push_str("    jmp .L_x86_split_cmp_loop\n");
    out.push_str(".L_x86_split_cmp_fail:\n");
    out.push_str("    incl -20(%ebp)\n");
    out.push_str("    jmp .L_x86_split_main_loop\n");
    out.push_str(".L_x86_split_matched:\n");
    out.push_str("    mov $alya_str_buf, %ecx\n");
    out.push_str("    mov alya_str_idx, %ebx\n");
    out.push_str("    cmp $48000, %ebx\n");
    out.push_str("    jl .L_x86_se2\n");
    out.push_str("    xor %ebx, %ebx\n");
    out.push_str(".L_x86_se2:\n");
    out.push_str("    lea (%ecx, %ebx), %edi\n");
    out.push_str("    mov %edi, -28(%ebp)\n");
    out.push_str("    mov -24(%ebp), %esi\n");
    out.push_str("    mov -20(%ebp), %edx\n");
    out.push_str(".L_x86_split_tok_copy:\n");
    out.push_str("    cmp %edx, %esi\n");
    out.push_str("    jge .L_x86_split_tok_done\n");
    out.push_str("    movb (%esi), %al\n");
    out.push_str("    movb %al, (%edi)\n");
    out.push_str("    inc %esi\n");
    out.push_str("    inc %edi\n");
    out.push_str("    jmp .L_x86_split_tok_copy\n");
    out.push_str(".L_x86_split_tok_done:\n");
    out.push_str("    movb $0, (%edi)\n");
    out.push_str("    inc %edi\n");
    out.push_str("    sub %ecx, %edi\n");
    out.push_str("    add $3, %edi\n");
    out.push_str("    and $-4, %edi\n");
    out.push_str("    mov %edi, alya_str_idx\n");
    out.push_str("    push -28(%ebp)\n");
    out.push_str("    push -12(%ebp)\n");
    out.push_str("    call alya_array_push\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    mov -16(%ebp), %eax\n");
    out.push_str("    add %eax, -20(%ebp)\n");
    out.push_str("    mov -20(%ebp), %eax\n");
    out.push_str("    mov %eax, -24(%ebp)\n");
    out.push_str("    jmp .L_x86_split_main_loop\n");
    out.push_str(".L_x86_split_emit_final:\n");
    out.push_str("    mov $alya_str_buf, %ecx\n");
    out.push_str("    mov alya_str_idx, %ebx\n");
    out.push_str("    cmp $48000, %ebx\n");
    out.push_str("    jl .L_x86_se3\n");
    out.push_str("    xor %ebx, %ebx\n");
    out.push_str(".L_x86_se3:\n");
    out.push_str("    lea (%ecx, %ebx), %edi\n");
    out.push_str("    mov %edi, -28(%ebp)\n");
    out.push_str("    mov -24(%ebp), %esi\n");
    out.push_str("    mov -20(%ebp), %edx\n");
    out.push_str(".L_x86_split_final_copy:\n");
    out.push_str("    cmp %edx, %esi\n");
    out.push_str("    jge .L_x86_split_final_done\n");
    out.push_str("    movb (%esi), %al\n");
    out.push_str("    movb %al, (%edi)\n");
    out.push_str("    inc %esi\n");
    out.push_str("    inc %edi\n");
    out.push_str("    jmp .L_x86_split_final_copy\n");
    out.push_str(".L_x86_split_final_done:\n");
    out.push_str("    movb $0, (%edi)\n");
    out.push_str("    inc %edi\n");
    out.push_str("    sub %ecx, %edi\n");
    out.push_str("    add $3, %edi\n");
    out.push_str("    and $-4, %edi\n");
    out.push_str("    mov %edi, alya_str_idx\n");
    out.push_str("    push -28(%ebp)\n");
    out.push_str("    push -12(%ebp)\n");
    out.push_str("    call alya_array_push\n");
    out.push_str("    add $8, %esp\n");
    out.push_str(".L_x86_split_ret:\n");
    out.push_str("    mov -12(%ebp), %eax\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // alya_map_hash
    out.push_str("alya_map_hash:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    mov 8(%ebp), %edx\n");
    out.push_str("    cmp $256, %edx\n");
    out.push_str("    jb .L_x86_mhash_int\n");
    out.push_str("    mov $5381, %eax\n");
    out.push_str(".L_x86_mhash_loop:\n");
    out.push_str("    movzbl (%edx), %ecx\n");
    out.push_str("    test %ecx, %ecx\n");
    out.push_str("    jz .L_x86_mhash_done\n");
    out.push_str("    mov %eax, %ebx\n");
    out.push_str("    shl $5, %ebx\n");
    out.push_str("    add %ebx, %eax\n");
    out.push_str("    add %ecx, %eax\n");
    out.push_str("    inc %edx\n");
    out.push_str("    jmp .L_x86_mhash_loop\n");
    out.push_str(".L_x86_mhash_int:\n");
    out.push_str("    mov %edx, %eax\n");
    out.push_str(".L_x86_mhash_done:\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // alya_map_key_eq / fn_streq
    out.push_str(".global fn_streq\n");
    out.push_str("fn_streq:\n");
    out.push_str(".global alya_map_key_eq\n");
    out.push_str("alya_map_key_eq:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov 8(%ebp), %esi\n");
    out.push_str("    mov 12(%ebp), %edi\n");
    out.push_str("    cmp %esi, %edi\n");
    out.push_str("    je .L_x86_mkeq_true\n");
    out.push_str("    cmp $256, %esi\n");
    out.push_str("    jb .L_x86_mkeq_false\n");
    out.push_str("    cmp $256, %edi\n");
    out.push_str("    jb .L_x86_mkeq_false\n");
    out.push_str(".L_x86_mkeq_str:\n");
    out.push_str("    movb (%esi), %al\n");
    out.push_str("    movb (%edi), %cl\n");
    out.push_str("    cmp %al, %cl\n");
    out.push_str("    jne .L_x86_mkeq_false\n");
    out.push_str("    test %al, %al\n");
    out.push_str("    jz .L_x86_mkeq_true\n");
    out.push_str("    inc %esi\n");
    out.push_str("    inc %edi\n");
    out.push_str("    jmp .L_x86_mkeq_str\n");
    out.push_str(".L_x86_mkeq_true:\n");
    out.push_str("    mov $1, %eax\n");
    out.push_str("    jmp .L_x86_mkeq_end\n");
    out.push_str(".L_x86_mkeq_false:\n");
    out.push_str("    xor %eax, %eax\n");
    out.push_str(".L_x86_mkeq_end:\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_map
    out.push_str("fn_map:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push $12\n");
    out.push_str("    push $1\n");
    out.push_str("    call calloc\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    mov %eax, %ebx\n"); // ebx = map header
    out.push_str("    movl $0, (%ebx)\n"); // len = 0
    out.push_str("    movl $64, 4(%ebx)\n"); // cap = 64
    out.push_str("    push $12\n");
    out.push_str("    push $64\n");
    out.push_str("    call calloc\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    mov %eax, 8(%ebx)\n"); // entries
    out.push_str("    mov %ebx, %eax\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_set
    out.push_str("fn_set:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    sub $16, %esp\n"); // -16: first_tombstone, -20: slot, -24: mask, -28: count
    out.push_str("    mov 8(%ebp), %esi\n"); // esi = map
    out.push_str("    test %esi, %esi\n");
    out.push_str("    jz .L_x86_set_done\n");
    // check resize: if len * 2 >= cap
    out.push_str("    mov (%esi), %eax\n");
    out.push_str("    shl $1, %eax\n");
    out.push_str("    cmp 4(%esi), %eax\n");
    out.push_str("    jl .L_x86_set_no_resize\n");
    // Resize table
    out.push_str("    mov 4(%esi), %eax\n");
    out.push_str("    shl $1, %eax\n"); // new_cap
    out.push_str("    mov %eax, %ebx\n"); // ebx = new_cap
    out.push_str("    push $12\n");
    out.push_str("    push %ebx\n");
    out.push_str("    call calloc\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    mov %eax, %edi\n"); // edi = new_entries
    out.push_str("    lea -1(%ebx), %edx\n"); // edx = new_mask
                                              // rehash old entries
    out.push_str("    mov 8(%esi), %ecx\n"); // ecx = old_entries
    out.push_str("    xor %eax, %eax\n"); // eax = i
    out.push_str(".L_x86_rehash_loop:\n");
    out.push_str("    cmp 4(%esi), %eax\n");
    out.push_str("    jge .L_x86_rehash_done\n");
    out.push_str("    lea (%eax, %eax, 2), %ebx\n");
    out.push_str("    shl $2, %ebx\n");
    out.push_str("    add %ecx, %ebx\n"); // ebx = &old_entries[i]
    out.push_str("    cmpl $1, 8(%ebx)\n");
    out.push_str("    jne .L_x86_rehash_next\n");
    // hash old key
    out.push_str("    push %eax\n");
    out.push_str("    push %ecx\n");
    out.push_str("    push %edx\n");
    out.push_str("    push (%ebx)\n");
    out.push_str("    call alya_map_hash\n");
    out.push_str("    add $4, %esp\n");
    out.push_str("    pop %edx\n");
    out.push_str("    pop %ecx\n");
    out.push_str("    and %edx, %eax\n"); // new_slot in eax
    out.push_str(".L_x86_rehash_probe:\n");
    out.push_str("    lea (%eax, %eax, 2), %r8d\n");
    out.push_str("    shl $2, %r8d\n");
    out.push_str("    add %edi, %r8d\n"); // r8d = &new_entries[slot]
    out.push_str("    cmpl $0, 8(%r8d)\n");
    out.push_str("    je .L_x86_rehash_put\n");
    out.push_str("    inc %eax\n");
    out.push_str("    and %edx, %eax\n");
    out.push_str("    jmp .L_x86_rehash_probe\n");
    out.push_str(".L_x86_rehash_put:\n");
    out.push_str("    mov (%ebx), %r9d\n");
    out.push_str("    mov %r9d, (%r8d)\n");
    out.push_str("    mov 4(%ebx), %r9d\n");
    out.push_str("    mov %r9d, 4(%r8d)\n");
    out.push_str("    movl $1, 8(%r8d)\n");
    out.push_str("    pop %eax\n");
    out.push_str(".L_x86_rehash_next:\n");
    out.push_str("    inc %eax\n");
    out.push_str("    jmp .L_x86_rehash_loop\n");
    out.push_str(".L_x86_rehash_done:\n");
    out.push_str("    mov 4(%esi), %eax\n");
    out.push_str("    shl $1, %eax\n");
    out.push_str("    mov %eax, 4(%esi)\n"); // cap = new_cap
    out.push_str("    mov %edi, 8(%esi)\n"); // entries = new_entries
    out.push_str(".L_x86_set_no_resize:\n");
    out.push_str("    mov 4(%esi), %eax\n");
    out.push_str("    dec %eax\n");
    out.push_str("    mov %eax, -24(%ebp)\n"); // mask
    out.push_str("    push 12(%ebp)\n");
    out.push_str("    call alya_map_hash\n");
    out.push_str("    add $4, %esp\n");
    out.push_str("    and -24(%ebp), %eax\n");
    out.push_str("    mov %eax, -20(%ebp)\n"); // slot
    out.push_str("    movl $-1, -16(%ebp)\n"); // first_tombstone = -1
    out.push_str("    movl $0, -28(%ebp)\n"); // count = 0
    out.push_str(".L_x86_set_probe:\n");
    out.push_str("    mov -28(%ebp), %eax\n");
    out.push_str("    cmp 4(%esi), %eax\n");
    out.push_str("    jge .L_x86_set_use_tomb\n");
    out.push_str("    mov -20(%ebp), %eax\n");
    out.push_str("    lea (%eax, %eax, 2), %edi\n");
    out.push_str("    shl $2, %edi\n");
    out.push_str("    add 8(%esi), %edi\n"); // edi = &entries[slot]
    out.push_str("    mov 8(%edi), %eax\n"); // flag
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jz .L_x86_set_empty\n");
    out.push_str("    cmp $2, %eax\n");
    out.push_str("    jne .L_x86_set_check_key\n");
    out.push_str("    cmpl $-1, -16(%ebp)\n");
    out.push_str("    jne .L_x86_set_next\n");
    out.push_str("    mov -20(%ebp), %eax\n");
    out.push_str("    mov %eax, -16(%ebp)\n");
    out.push_str("    jmp .L_x86_set_next\n");
    out.push_str(".L_x86_set_check_key:\n");
    out.push_str("    push (%edi)\n");
    out.push_str("    push 12(%ebp)\n");
    out.push_str("    call alya_map_key_eq\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jz .L_x86_set_next\n");
    // Key match: update value
    out.push_str("    mov 16(%ebp), %eax\n");
    out.push_str("    mov %eax, 4(%edi)\n");
    out.push_str("    jmp .L_x86_set_done\n");
    out.push_str(".L_x86_set_next:\n");
    out.push_str("    incl -28(%ebp)\n");
    out.push_str("    mov -20(%ebp), %eax\n");
    out.push_str("    inc %eax\n");
    out.push_str("    and -24(%ebp), %eax\n");
    out.push_str("    mov %eax, -20(%ebp)\n");
    out.push_str("    jmp .L_x86_set_probe\n");
    out.push_str(".L_x86_set_empty:\n");
    out.push_str("    cmpl $-1, -16(%ebp)\n");
    out.push_str("    je .L_x86_set_insert_here\n");
    out.push_str(".L_x86_set_use_tomb:\n");
    out.push_str("    cmpl $-1, -16(%ebp)\n");
    out.push_str("    je .L_x86_set_done\n");
    out.push_str("    mov -16(%ebp), %eax\n");
    out.push_str("    lea (%eax, %eax, 2), %edi\n");
    out.push_str("    shl $2, %edi\n");
    out.push_str("    add 8(%esi), %edi\n");
    out.push_str(".L_x86_set_insert_here:\n");
    out.push_str("    mov 12(%ebp), %eax\n");
    out.push_str("    mov %eax, (%edi)\n");
    out.push_str("    mov 16(%ebp), %eax\n");
    out.push_str("    mov %eax, 4(%edi)\n");
    out.push_str("    movl $1, 8(%edi)\n");
    out.push_str("    incl (%esi)\n"); // len++
    out.push_str(".L_x86_set_done:\n");
    out.push_str("    add $16, %esp\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_get
    out.push_str("fn_get:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov 8(%ebp), %esi\n"); // esi = map
    out.push_str("    xor %eax, %eax\n");
    out.push_str("    test %esi, %esi\n");
    out.push_str("    jz .L_x86_get_ret\n");
    out.push_str("    push 12(%ebp)\n");
    out.push_str("    call alya_map_hash\n");
    out.push_str("    add $4, %esp\n");
    out.push_str("    mov 4(%esi), %edx\n"); // cap
    out.push_str("    dec %edx\n"); // mask
    out.push_str("    and %edx, %eax\n"); // slot
    out.push_str("    xor %ebx, %ebx\n"); // count
    out.push_str(".L_x86_get_loop:\n");
    out.push_str("    cmp 4(%esi), %ebx\n");
    out.push_str("    jge .L_x86_get_not_found\n");
    out.push_str("    lea (%eax, %eax, 2), %edi\n");
    out.push_str("    shl $2, %edi\n");
    out.push_str("    add 8(%esi), %edi\n");
    out.push_str("    cmpl $0, 8(%edi)\n");
    out.push_str("    je .L_x86_get_not_found\n");
    out.push_str("    cmpl $1, 8(%edi)\n");
    out.push_str("    jne .L_x86_get_next\n");
    out.push_str("    push %eax\n");
    out.push_str("    push %edx\n");
    out.push_str("    push (%edi)\n");
    out.push_str("    push 12(%ebp)\n");
    out.push_str("    call alya_map_key_eq\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    pop %edx\n");
    out.push_str("    pop %eax\n");
    out.push_str("    jnz .L_x86_get_found\n");
    out.push_str(".L_x86_get_next:\n");
    out.push_str("    inc %eax\n");
    out.push_str("    and %edx, %eax\n");
    out.push_str("    inc %ebx\n");
    out.push_str("    jmp .L_x86_get_loop\n");
    out.push_str(".L_x86_get_found:\n");
    out.push_str("    mov 4(%edi), %eax\n");
    out.push_str("    jmp .L_x86_get_ret\n");
    out.push_str(".L_x86_get_not_found:\n");
    out.push_str("    xor %eax, %eax\n");
    out.push_str(".L_x86_get_ret:\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_has
    out.push_str("fn_has:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov 8(%ebp), %esi\n");
    out.push_str("    xor %eax, %eax\n");
    out.push_str("    test %esi, %esi\n");
    out.push_str("    jz .L_x86_has_ret\n");
    out.push_str("    push 12(%ebp)\n");
    out.push_str("    call alya_map_hash\n");
    out.push_str("    add $4, %esp\n");
    out.push_str("    mov 4(%esi), %edx\n");
    out.push_str("    dec %edx\n");
    out.push_str("    and %edx, %eax\n");
    out.push_str("    xor %ebx, %ebx\n");
    out.push_str(".L_x86_has_loop:\n");
    out.push_str("    cmp 4(%esi), %ebx\n");
    out.push_str("    jge .L_x86_has_not_found\n");
    out.push_str("    lea (%eax, %eax, 2), %edi\n");
    out.push_str("    shl $2, %edi\n");
    out.push_str("    add 8(%esi), %edi\n");
    out.push_str("    cmpl $0, 8(%edi)\n");
    out.push_str("    je .L_x86_has_not_found\n");
    out.push_str("    cmpl $1, 8(%edi)\n");
    out.push_str("    jne .L_x86_has_next\n");
    out.push_str("    push %eax\n");
    out.push_str("    push %edx\n");
    out.push_str("    push (%edi)\n");
    out.push_str("    push 12(%ebp)\n");
    out.push_str("    call alya_map_key_eq\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    pop %edx\n");
    out.push_str("    pop %eax\n");
    out.push_str("    jnz .L_x86_has_found\n");
    out.push_str(".L_x86_has_next:\n");
    out.push_str("    inc %eax\n");
    out.push_str("    and %edx, %eax\n");
    out.push_str("    inc %ebx\n");
    out.push_str("    jmp .L_x86_has_loop\n");
    out.push_str(".L_x86_has_found:\n");
    out.push_str("    mov $1, %eax\n");
    out.push_str("    jmp .L_x86_has_ret\n");
    out.push_str(".L_x86_has_not_found:\n");
    out.push_str("    xor %eax, %eax\n");
    out.push_str(".L_x86_has_ret:\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_remove
    out.push_str("fn_remove:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov 8(%ebp), %esi\n");
    out.push_str("    xor %eax, %eax\n");
    out.push_str("    test %esi, %esi\n");
    out.push_str("    jz .L_x86_rem_ret\n");
    out.push_str("    push 12(%ebp)\n");
    out.push_str("    call alya_map_hash\n");
    out.push_str("    add $4, %esp\n");
    out.push_str("    mov 4(%esi), %edx\n");
    out.push_str("    dec %edx\n");
    out.push_str("    and %edx, %eax\n");
    out.push_str("    xor %ebx, %ebx\n");
    out.push_str(".L_x86_rem_loop:\n");
    out.push_str("    cmp 4(%esi), %ebx\n");
    out.push_str("    jge .L_x86_rem_not_found\n");
    out.push_str("    lea (%eax, %eax, 2), %edi\n");
    out.push_str("    shl $2, %edi\n");
    out.push_str("    add 8(%esi), %edi\n");
    out.push_str("    cmpl $0, 8(%edi)\n");
    out.push_str("    je .L_x86_rem_not_found\n");
    out.push_str("    cmpl $1, 8(%edi)\n");
    out.push_str("    jne .L_x86_rem_next\n");
    out.push_str("    push %eax\n");
    out.push_str("    push %edx\n");
    out.push_str("    push (%edi)\n");
    out.push_str("    push 12(%ebp)\n");
    out.push_str("    call alya_map_key_eq\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    pop %edx\n");
    out.push_str("    pop %eax\n");
    out.push_str("    jnz .L_x86_rem_found\n");
    out.push_str(".L_x86_rem_next:\n");
    out.push_str("    inc %eax\n");
    out.push_str("    and %edx, %eax\n");
    out.push_str("    inc %ebx\n");
    out.push_str("    jmp .L_x86_rem_loop\n");
    out.push_str(".L_x86_rem_found:\n");
    out.push_str("    movl $2, 8(%edi)\n"); // tombstone
    out.push_str("    decl (%esi)\n"); // len--
    out.push_str("    mov $1, %eax\n");
    out.push_str("    jmp .L_x86_rem_ret\n");
    out.push_str(".L_x86_rem_not_found:\n");
    out.push_str("    xor %eax, %eax\n");
    out.push_str(".L_x86_rem_ret:\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_keys
    out.push_str("fn_keys:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov 8(%ebp), %esi\n");
    out.push_str("    push $0\n");
    out.push_str("    call alya_array_new\n");
    out.push_str("    add $4, %esp\n");
    out.push_str("    mov %eax, %ebx\n"); // ebx = array
    out.push_str("    test %esi, %esi\n");
    out.push_str("    jz .L_x86_keys_done\n");
    out.push_str("    mov 8(%esi), %edi\n"); // edi = entries
    out.push_str("    xor %ecx, %ecx\n"); // ecx = i
    out.push_str(".L_x86_keys_loop:\n");
    out.push_str("    cmp 4(%esi), %ecx\n");
    out.push_str("    jge .L_x86_keys_done\n");
    out.push_str("    cmpl $1, 8(%edi)\n");
    out.push_str("    jne .L_x86_keys_next\n");
    out.push_str("    push %ecx\n");
    out.push_str("    push (%edi)\n");
    out.push_str("    push %ebx\n");
    out.push_str("    call alya_array_push\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    pop %ecx\n");
    out.push_str(".L_x86_keys_next:\n");
    out.push_str("    add $12, %edi\n");
    out.push_str("    inc %ecx\n");
    out.push_str("    jmp .L_x86_keys_loop\n");
    out.push_str(".L_x86_keys_done:\n");
    out.push_str("    mov %ebx, %eax\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_values
    out.push_str("fn_values:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov 8(%ebp), %esi\n");
    out.push_str("    push $0\n");
    out.push_str("    call alya_array_new\n");
    out.push_str("    add $4, %esp\n");
    out.push_str("    mov %eax, %ebx\n");
    out.push_str("    test %esi, %esi\n");
    out.push_str("    jz .L_x86_vals_done\n");
    out.push_str("    mov 8(%esi), %edi\n");
    out.push_str("    xor %ecx, %ecx\n");
    out.push_str(".L_x86_vals_loop:\n");
    out.push_str("    cmp 4(%esi), %ecx\n");
    out.push_str("    jge .L_x86_vals_done\n");
    out.push_str("    cmpl $1, 8(%edi)\n");
    out.push_str("    jne .L_x86_vals_next\n");
    out.push_str("    push %ecx\n");
    out.push_str("    push 4(%edi)\n");
    out.push_str("    push %ebx\n");
    out.push_str("    call alya_array_push\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    pop %ecx\n");
    out.push_str(".L_x86_vals_next:\n");
    out.push_str("    add $12, %edi\n");
    out.push_str("    inc %ecx\n");
    out.push_str("    jmp .L_x86_vals_loop\n");
    out.push_str(".L_x86_vals_done:\n");
    out.push_str("    mov %ebx, %eax\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // alya_print_map
    out.push_str("alya_print_map:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov 8(%ebp), %esi\n");
    out.push_str("    test %esi, %esi\n");
    out.push_str("    jnz .L_x86_pmap_not_null\n");
    out.push_str("    push $alya_fmt_map_null\n");
    out.push_str("    call printf\n");
    out.push_str("    add $4, %esp\n");
    out.push_str("    jmp .L_x86_pmap_exit\n");
    out.push_str(".L_x86_pmap_not_null:\n");
    out.push_str("    cmpl $0, (%esi)\n");
    out.push_str("    jne .L_x86_pmap_has_items\n");
    out.push_str("    push $alya_fmt_map_empty\n");
    out.push_str("    call printf\n");
    out.push_str("    add $4, %esp\n");
    out.push_str("    jmp .L_x86_pmap_exit\n");
    out.push_str(".L_x86_pmap_has_items:\n");
    out.push_str("    push $alya_fmt_map_open\n");
    out.push_str("    call printf\n");
    out.push_str("    add $4, %esp\n");
    out.push_str("    xor %ebx, %ebx\n"); // printed = 0
    out.push_str("    mov 8(%esi), %edi\n"); // edi = entries
    out.push_str("    xor %ecx, %ecx\n"); // ecx = slot
    out.push_str(".L_x86_pmap_loop:\n");
    out.push_str("    cmp 4(%esi), %ecx\n");
    out.push_str("    jge .L_x86_pmap_close\n");
    out.push_str("    cmpl $1, 8(%edi)\n");
    out.push_str("    jne .L_x86_pmap_next\n");
    out.push_str("    test %ebx, %ebx\n");
    out.push_str("    jz .L_x86_pmap_print_pair\n");
    out.push_str("    push %ecx\n");
    out.push_str("    push $alya_fmt_arr_comma\n");
    out.push_str("    call printf\n");
    out.push_str("    add $4, %esp\n");
    out.push_str("    pop %ecx\n");
    out.push_str(".L_x86_pmap_print_pair:\n");
    out.push_str("    push %ecx\n");
    out.push_str("    mov (%edi), %eax\n"); // key
    out.push_str("    cmp $256, %eax\n");
    out.push_str("    jb .L_x86_pmap_key_num\n");
    out.push_str("    push %eax\n");
    out.push_str("    push $alya_fmt_prompt\n");
    out.push_str("    call printf\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    jmp .L_x86_pmap_colon\n");
    out.push_str(".L_x86_pmap_key_num:\n");
    out.push_str("    push %eax\n");
    out.push_str("    push $alya_fmt_arr_elem\n");
    out.push_str("    call printf\n");
    out.push_str("    add $8, %esp\n");
    out.push_str(".L_x86_pmap_colon:\n");
    out.push_str("    push $alya_fmt_map_colon\n");
    out.push_str("    call printf\n");
    out.push_str("    add $4, %esp\n");
    out.push_str("    mov 4(%edi), %eax\n"); // val
    out.push_str("    push %eax\n");
    out.push_str("    push $alya_fmt_arr_elem\n");
    out.push_str("    call printf\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    pop %ecx\n");
    out.push_str("    inc %ebx\n");
    out.push_str(".L_x86_pmap_next:\n");
    out.push_str("    add $12, %edi\n");
    out.push_str("    inc %ecx\n");
    out.push_str("    jmp .L_x86_pmap_loop\n");
    out.push_str(".L_x86_pmap_close:\n");
    out.push_str("    push $alya_fmt_map_close\n");
    out.push_str("    call printf\n");
    out.push_str("    add $4, %esp\n");
    out.push_str(".L_x86_pmap_exit:\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");
}
