use crate::codegen::target::OperatingSystem;
use super::emit_adrp_add;

#[rustfmt::skip]
pub fn emit(out: &mut String, os: OperatingSystem) {
    let is_win = matches!(os, OperatingSystem::Windows);
    let p = if matches!(os, OperatingSystem::MacOS) { "_" } else { "" };
    let _ = (is_win, p);

    // alya_concat
    out.push_str(".align 2\n");
    out.push_str("alya_concat:\n");
    out.push_str("    stp x29, x30, [sp, #-16]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    stp x19, x20, [sp, #-16]!\n");
    out.push_str("    stp x21, x22, [sp, #-16]!\n");
    emit_adrp_add(out, "x19", "alya_str_buf", os);
    emit_adrp_add(out, "x20", "alya_str_idx", os);
    out.push_str("    ldr x21, [x20]\n");
    out.push_str("    mov x9, #48000\n");
    out.push_str("    cmp x21, x9\n");
    out.push_str("    b.lt .L_arm_concat_ok\n");
    out.push_str("    mov x21, #0\n");
    out.push_str(".L_arm_concat_ok:\n");
    out.push_str("    add x22, x19, x21\n");
    out.push_str(".L_arm_copy1:\n");
    out.push_str("    ldrb w2, [x0], #1\n");
    out.push_str("    cbz w2, .L_arm_copy2_start\n");
    out.push_str("    strb w2, [x22], #1\n");
    out.push_str("    b .L_arm_copy1\n");
    out.push_str(".L_arm_copy2_start:\n");
    out.push_str(".L_arm_copy2:\n");
    out.push_str("    ldrb w2, [x1], #1\n");
    out.push_str("    cbz w2, .L_arm_concat_end\n");
    out.push_str("    strb w2, [x22], #1\n");
    out.push_str("    b .L_arm_copy2\n");
    out.push_str(".L_arm_concat_end:\n");
    out.push_str("    strb wzr, [x22], #1\n");
    out.push_str("    sub x2, x22, x19\n");
    out.push_str("    add x2, x2, #7\n");
    out.push_str("    and x2, x2, #~7\n");
    out.push_str("    str x2, [x20]\n");
    out.push_str("    add x0, x19, x21\n");
    out.push_str("    ldp x21, x22, [sp], #16\n");
    out.push_str("    ldp x19, x20, [sp], #16\n");
    out.push_str("    ldp x29, x30, [sp], #16\n");
    out.push_str("    ret\n\n");

    // fn_len
    out.push_str("fn_len:\n");
    out.push_str("    mov x1, x0\n");
    out.push_str("    mov x0, #0\n");
    out.push_str(".L_arm_len_loop:\n");
    out.push_str("    ldrb w2, [x1, x0]\n");
    out.push_str("    cbz w2, .L_arm_len_end\n");
    out.push_str("    add x0, x0, #1\n");
    out.push_str("    b .L_arm_len_loop\n");
    out.push_str(".L_arm_len_end:\n");
    out.push_str("    ret\n\n");

    // fn_ask
    out.push_str("fn_ask:\n");
    out.push_str("    stp x29, x30, [sp, #-16]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    stp x19, x20, [sp, #-16]!\n");
    out.push_str("    stp x21, x22, [sp, #-16]!\n");
    out.push_str("    cbz x0, .L_arm_ask_read\n");
    out.push_str("    mov x1, x0\n");
    emit_adrp_add(out, "x0", "alya_fmt_prompt", os);
    if matches!(os, OperatingSystem::MacOS) {
        out.push_str("    sub sp, sp, #16\n");
        out.push_str("    str x1, [sp]\n");
        out.push_str(&format!("    bl {}printf\n", p));
        out.push_str("    add sp, sp, #16\n");
    } else {
        out.push_str(&format!("    bl {}printf\n", p));
    }
    out.push_str("    mov x0, #0\n");
    out.push_str(&format!("    bl {}fflush\n", p));
    out.push_str(".L_arm_ask_read:\n");
    emit_adrp_add(out, "x19", "alya_str_buf", os);
    emit_adrp_add(out, "x20", "alya_str_idx", os);
    out.push_str("    ldr x2, [x20]\n");
    out.push_str("    mov x9, #48000\n");
    out.push_str("    cmp x2, x9\n");
    out.push_str("    b.lt .L_arm_ask_buf_ok\n");
    out.push_str("    mov x2, #0\n");
    out.push_str(".L_arm_ask_buf_ok:\n");
    out.push_str("    add x19, x19, x2\n");
    out.push_str("    mov x21, x19\n");
    out.push_str(".L_arm_ask_loop:\n");
    out.push_str(&format!("    bl {}getchar\n", p));
    out.push_str("    cmp w0, #-1\n");
    out.push_str("    b.eq .L_arm_ask_done\n");
    out.push_str("    cmp w0, #10\n");
    out.push_str("    b.eq .L_arm_ask_done\n");
    out.push_str("    cmp w0, #13\n");
    out.push_str("    b.eq .L_arm_ask_loop\n");
    out.push_str("    strb w0, [x19], #1\n");
    out.push_str("    b .L_arm_ask_loop\n");
    out.push_str(".L_arm_ask_done:\n");
    out.push_str("    strb wzr, [x19], #1\n");
    emit_adrp_add(out, "x1", "alya_str_buf", os);
    out.push_str("    sub x2, x19, x1\n");
    out.push_str("    add x2, x2, #7\n");
    out.push_str("    and x2, x2, #~7\n");
    out.push_str("    str x2, [x20]\n");
    out.push_str("    mov x0, x21\n");
    out.push_str("    ldp x21, x22, [sp], #16\n");
    out.push_str("    ldp x19, x20, [sp], #16\n");
    out.push_str("    ldp x29, x30, [sp], #16\n");
    out.push_str("    ret\n\n");

    // fn_upper
    out.push_str(".align 2\n");
    out.push_str("fn_upper:\n");
    out.push_str("    stp x29, x30, [sp, #-48]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    stp x19, x20, [sp, #16]\n");
    out.push_str("    stp x21, x22, [sp, #32]\n");
    out.push_str("    mov x19, x0\n");
    emit_adrp_add(out, "x20", "alya_str_buf", os);
    emit_adrp_add(out, "x21", "alya_str_idx", os);
    out.push_str("    ldr x22, [x21]\n");
    out.push_str("    mov x9, #48000\n");
    out.push_str("    cmp x22, x9\n");
    out.push_str("    b.lt .L_arm64_upper_buf_ok\n");
    out.push_str("    mov x22, #0\n");
    out.push_str(".L_arm64_upper_buf_ok:\n");
    out.push_str("    add x0, x20, x22\n");
    out.push_str("    mov x10, x0\n");
    out.push_str(".L_arm64_upper_loop:\n");
    out.push_str("    ldrb w11, [x19], #1\n");
    out.push_str("    cbz w11, .L_arm64_upper_done\n");
    out.push_str("    cmp w11, #'a'\n");
    out.push_str("    b.lt .L_arm64_upper_store\n");
    out.push_str("    cmp w11, #'z'\n");
    out.push_str("    b.gt .L_arm64_upper_store\n");
    out.push_str("    sub w11, w11, #32\n");
    out.push_str(".L_arm64_upper_store:\n");
    out.push_str("    strb w11, [x10], #1\n");
    out.push_str("    b .L_arm64_upper_loop\n");
    out.push_str(".L_arm64_upper_done:\n");
    out.push_str("    strb wzr, [x10], #1\n");
    out.push_str("    sub x11, x10, x20\n");
    out.push_str("    add x11, x11, #7\n");
    out.push_str("    and x11, x11, #~7\n");
    out.push_str("    str x11, [x21]\n");
    out.push_str("    ldp x21, x22, [sp, #32]\n");
    out.push_str("    ldp x19, x20, [sp, #16]\n");
    out.push_str("    ldp x29, x30, [sp], #48\n");
    out.push_str("    ret\n\n");

    // fn_lower
    out.push_str(".align 2\n");
    out.push_str("fn_lower:\n");
    out.push_str("    stp x29, x30, [sp, #-48]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    stp x19, x20, [sp, #16]\n");
    out.push_str("    stp x21, x22, [sp, #32]\n");
    out.push_str("    mov x19, x0\n");
    emit_adrp_add(out, "x20", "alya_str_buf", os);
    emit_adrp_add(out, "x21", "alya_str_idx", os);
    out.push_str("    ldr x22, [x21]\n");
    out.push_str("    mov x9, #48000\n");
    out.push_str("    cmp x22, x9\n");
    out.push_str("    b.lt .L_arm64_lower_buf_ok\n");
    out.push_str("    mov x22, #0\n");
    out.push_str(".L_arm64_lower_buf_ok:\n");
    out.push_str("    add x0, x20, x22\n");
    out.push_str("    mov x10, x0\n");
    out.push_str(".L_arm64_lower_loop:\n");
    out.push_str("    ldrb w11, [x19], #1\n");
    out.push_str("    cbz w11, .L_arm64_lower_done\n");
    out.push_str("    cmp w11, #'A'\n");
    out.push_str("    b.lt .L_arm64_lower_store\n");
    out.push_str("    cmp w11, #'Z'\n");
    out.push_str("    b.gt .L_arm64_lower_store\n");
    out.push_str("    add w11, w11, #32\n");
    out.push_str(".L_arm64_lower_store:\n");
    out.push_str("    strb w11, [x10], #1\n");
    out.push_str("    b .L_arm64_lower_loop\n");
    out.push_str(".L_arm64_lower_done:\n");
    out.push_str("    strb wzr, [x10], #1\n");
    out.push_str("    sub x11, x10, x20\n");
    out.push_str("    add x11, x11, #7\n");
    out.push_str("    and x11, x11, #~7\n");
    out.push_str("    str x11, [x21]\n");
    out.push_str("    ldp x21, x22, [sp, #32]\n");
    out.push_str("    ldp x19, x20, [sp, #16]\n");
    out.push_str("    ldp x29, x30, [sp], #48\n");
    out.push_str("    ret\n\n");

    // fn_trim
    out.push_str(".align 2\n");
    out.push_str("fn_trim:\n");
    out.push_str("    stp x29, x30, [sp, #-48]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    stp x19, x20, [sp, #16]\n");
    out.push_str("    stp x21, x22, [sp, #32]\n");
    out.push_str("    mov x19, x0\n");
    out.push_str(".L_arm64_trim_lws:\n");
    out.push_str("    ldrb w11, [x19]\n");
    out.push_str("    cmp w11, #32\n");
    out.push_str("    b.eq .L_arm64_trim_lws_inc\n");
    out.push_str("    cmp w11, #9\n");
    out.push_str("    b.eq .L_arm64_trim_lws_inc\n");
    out.push_str("    cmp w11, #10\n");
    out.push_str("    b.eq .L_arm64_trim_lws_inc\n");
    out.push_str("    cmp w11, #13\n");
    out.push_str("    b.eq .L_arm64_trim_lws_inc\n");
    out.push_str("    b .L_arm64_trim_lws_done\n");
    out.push_str(".L_arm64_trim_lws_inc:\n");
    out.push_str("    add x19, x19, #1\n");
    out.push_str("    b .L_arm64_trim_lws\n");
    out.push_str(".L_arm64_trim_lws_done:\n");
    out.push_str("    mov x12, x19\n");
    out.push_str(".L_arm64_trim_end_loop:\n");
    out.push_str("    ldrb w11, [x12]\n");
    out.push_str("    cbz w11, .L_arm64_trim_find_end_done\n");
    out.push_str("    add x12, x12, #1\n");
    out.push_str("    b .L_arm64_trim_end_loop\n");
    out.push_str(".L_arm64_trim_find_end_done:\n");
    out.push_str(".L_arm64_trim_tws:\n");
    out.push_str("    cmp x12, x19\n");
    out.push_str("    b.le .L_arm64_trim_copy_start\n");
    out.push_str("    sub x13, x12, #1\n");
    out.push_str("    ldrb w11, [x13]\n");
    out.push_str("    cmp w11, #32\n");
    out.push_str("    b.eq .L_arm64_trim_tws_dec\n");
    out.push_str("    cmp w11, #9\n");
    out.push_str("    b.eq .L_arm64_trim_tws_dec\n");
    out.push_str("    cmp w11, #10\n");
    out.push_str("    b.eq .L_arm64_trim_tws_dec\n");
    out.push_str("    cmp w11, #13\n");
    out.push_str("    b.eq .L_arm64_trim_tws_dec\n");
    out.push_str("    b .L_arm64_trim_copy_start\n");
    out.push_str(".L_arm64_trim_tws_dec:\n");
    out.push_str("    mov x12, x13\n");
    out.push_str("    b .L_arm64_trim_tws\n");
    out.push_str(".L_arm64_trim_copy_start:\n");
    emit_adrp_add(out, "x20", "alya_str_buf", os);
    emit_adrp_add(out, "x21", "alya_str_idx", os);
    out.push_str("    ldr x22, [x21]\n");
    out.push_str("    mov x9, #48000\n");
    out.push_str("    cmp x22, x9\n");
    out.push_str("    b.lt .L_arm64_trim_buf_ok\n");
    out.push_str("    mov x22, #0\n");
    out.push_str(".L_arm64_trim_buf_ok:\n");
    out.push_str("    add x0, x20, x22\n");
    out.push_str("    mov x10, x0\n");
    out.push_str(".L_arm64_trim_copy_loop:\n");
    out.push_str("    cmp x19, x12\n");
    out.push_str("    b.ge .L_arm64_trim_done\n");
    out.push_str("    ldrb w11, [x19], #1\n");
    out.push_str("    strb w11, [x10], #1\n");
    out.push_str("    b .L_arm64_trim_copy_loop\n");
    out.push_str(".L_arm64_trim_done:\n");
    out.push_str("    strb wzr, [x10], #1\n");
    out.push_str("    sub x11, x10, x20\n");
    out.push_str("    add x11, x11, #7\n");
    out.push_str("    and x11, x11, #~7\n");
    out.push_str("    str x11, [x21]\n");
    out.push_str("    ldp x21, x22, [sp, #32]\n");
    out.push_str("    ldp x19, x20, [sp, #16]\n");
    out.push_str("    ldp x29, x30, [sp], #48\n");
    out.push_str("    ret\n\n");

    // fn_contains
    out.push_str(".align 2\n");
    out.push_str("fn_contains:\n");
    out.push_str("    ldrb w2, [x1]\n");
    out.push_str("    cbz w2, .L_arm64_contains_match\n");
    out.push_str(".L_arm64_contains_outer:\n");
    out.push_str("    ldrb w2, [x0]\n");
    out.push_str("    cbz w2, .L_arm64_contains_nomatch\n");
    out.push_str("    mov x3, x0\n");
    out.push_str("    mov x4, x1\n");
    out.push_str(".L_arm64_contains_inner:\n");
    out.push_str("    ldrb w5, [x4]\n");
    out.push_str("    cbz w5, .L_arm64_contains_match\n");
    out.push_str("    ldrb w6, [x3]\n");
    out.push_str("    cmp w6, w5\n");
    out.push_str("    b.ne .L_arm64_contains_next\n");
    out.push_str("    add x3, x3, #1\n");
    out.push_str("    add x4, x4, #1\n");
    out.push_str("    b .L_arm64_contains_inner\n");
    out.push_str(".L_arm64_contains_next:\n");
    out.push_str("    add x0, x0, #1\n");
    out.push_str("    b .L_arm64_contains_outer\n");
    out.push_str(".L_arm64_contains_match:\n");
    out.push_str("    mov x0, #1\n");
    out.push_str("    ret\n");
    out.push_str(".L_arm64_contains_nomatch:\n");
    out.push_str("    mov x0, #0\n");
    out.push_str("    ret\n\n");

    // fn_substring / fn_substr
    out.push_str(".align 2\n");
    out.push_str("fn_substr:\n");
    out.push_str(".align 2\n");
    out.push_str("fn_substring:\n");
    out.push_str("    stp x29, x30, [sp, #-48]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    stp x19, x20, [sp, #16]\n");
    out.push_str("    stp x21, x22, [sp, #32]\n");
    out.push_str("    mov x19, x0\n");
    out.push_str("    cmp x1, #0\n");
    out.push_str("    b.ge .L_arm64_sub_adv\n");
    out.push_str("    mov x1, #0\n");
    out.push_str(".L_arm64_sub_adv:\n");
    out.push_str("    cbz x1, .L_arm64_sub_adv_done\n");
    out.push_str("    ldrb w3, [x19]\n");
    out.push_str("    cbz w3, .L_arm64_sub_adv_done\n");
    out.push_str("    add x19, x19, #1\n");
    out.push_str("    sub x1, x1, #1\n");
    out.push_str("    b .L_arm64_sub_adv\n");
    out.push_str(".L_arm64_sub_adv_done:\n");
    emit_adrp_add(out, "x20", "alya_str_buf", os);
    emit_adrp_add(out, "x21", "alya_str_idx", os);
    out.push_str("    ldr x22, [x21]\n");
    out.push_str("    mov x9, #48000\n");
    out.push_str("    cmp x22, x9\n");
    out.push_str("    b.lt .L_arm64_sub_buf_ok\n");
    out.push_str("    mov x22, #0\n");
    out.push_str(".L_arm64_sub_buf_ok:\n");
    out.push_str("    add x0, x20, x22\n");
    out.push_str("    mov x10, x0\n");
    out.push_str(".L_arm64_sub_copy:\n");
    out.push_str("    ldrb w3, [x19]\n");
    out.push_str("    cbz w3, .L_arm64_sub_done\n");
    out.push_str("    cbz x2, .L_arm64_sub_done\n");
    out.push_str("    strb w3, [x10], #1\n");
    out.push_str("    add x19, x19, #1\n");
    out.push_str("    cmp x2, #0\n");
    out.push_str("    b.lt .L_arm64_sub_copy\n");
    out.push_str("    sub x2, x2, #1\n");
    out.push_str("    b .L_arm64_sub_copy\n");
    out.push_str(".L_arm64_sub_done:\n");
    out.push_str("    strb wzr, [x10], #1\n");
    out.push_str("    sub x11, x10, x20\n");
    out.push_str("    add x11, x11, #7\n");
    out.push_str("    and x11, x11, #~7\n");
    out.push_str("    str x11, [x21]\n");
    out.push_str("    ldp x21, x22, [sp, #32]\n");
    out.push_str("    ldp x19, x20, [sp, #16]\n");
    out.push_str("    ldp x29, x30, [sp], #48\n");
    out.push_str("    ret\n\n");

    // fn_char_at
    out.push_str(".align 2\n");
    out.push_str("fn_char_at:\n");
    out.push_str("    stp x29, x30, [sp, #-48]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    stp x19, x20, [sp, #16]\n");
    out.push_str("    stp x21, x22, [sp, #32]\n");
    out.push_str("    mov x19, x0\n");
    out.push_str("    mov x20, x1\n");
    out.push_str("    cbz x19, .L_arm64_char_at_empty\n");
    out.push_str("    cmp x20, #0\n");
    out.push_str("    b.lt .L_arm64_char_at_empty\n");
    out.push_str(".L_arm64_char_at_adv:\n");
    out.push_str("    cbz x20, .L_arm64_char_at_fetch\n");
    out.push_str("    ldrb w2, [x19]\n");
    out.push_str("    cbz w2, .L_arm64_char_at_empty\n");
    out.push_str("    add x19, x19, #1\n");
    out.push_str("    sub x20, x20, #1\n");
    out.push_str("    b .L_arm64_char_at_adv\n");
    out.push_str(".L_arm64_char_at_fetch:\n");
    out.push_str("    ldrb w2, [x19]\n");
    out.push_str("    cbz w2, .L_arm64_char_at_empty\n");
    emit_adrp_add(out, "x3", "alya_str_buf", os);
    emit_adrp_add(out, "x4", "alya_str_idx", os);
    out.push_str("    ldr x5, [x4]\n");
    out.push_str("    mov x6, #48000\n");
    out.push_str("    cmp x5, x6\n");
    out.push_str("    b.lt .L_arm64_char_at_buf_ok\n");
    out.push_str("    mov x5, #0\n");
    out.push_str(".L_arm64_char_at_buf_ok:\n");
    out.push_str("    add x0, x3, x5\n");
    out.push_str("    strb w2, [x0]\n");
    out.push_str("    strb wzr, [x0, #1]\n");
    out.push_str("    add x5, x5, #2\n");
    out.push_str("    add x5, x5, #7\n");
    out.push_str("    and x5, x5, #~7\n");
    out.push_str("    str x5, [x4]\n");
    out.push_str("    b .L_arm64_char_at_done\n");
    out.push_str(".L_arm64_char_at_empty:\n");
    emit_adrp_add(out, "x0", "alya_str_empty", os);
    out.push_str(".L_arm64_char_at_done:\n");
    out.push_str("    ldp x21, x22, [sp, #32]\n");
    out.push_str("    ldp x19, x20, [sp, #16]\n");
    out.push_str("    ldp x29, x30, [sp], #48\n");
    out.push_str("    ret\n\n");

    // fn_ord / fn_char_code
    out.push_str(".align 2\n");
    out.push_str("fn_char_code:\n");
    out.push_str("fn_ord:\n");
    out.push_str("    cbz x0, .L_arm64_ord_ret\n");
    out.push_str("    cmp x0, #256\n");
    out.push_str("    b.lo .L_arm64_ord_ret\n");
    out.push_str("    ldrb w0, [x0]\n");
    out.push_str(".L_arm64_ord_ret:\n");
    out.push_str("    ret\n\n");

    // fn_chr / fn_char_from_code
    out.push_str(".align 2\n");
    out.push_str("fn_char_from_code:\n");
    out.push_str("fn_chr:\n");
    out.push_str("    stp x29, x30, [sp, #-32]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    stp x19, x20, [sp, #16]\n");
    out.push_str("    mov x19, x0\n");
    out.push_str("    cbz x19, .L_arm64_chr_empty\n");
    out.push_str("    cmp x19, #256\n");
    out.push_str("    b.lo .L_arm64_chr_byte\n");
    out.push_str("    ldrb w19, [x19]\n");
    out.push_str(".L_arm64_chr_byte:\n");
    out.push_str("    and w19, w19, #255\n");
    out.push_str("    cbz w19, .L_arm64_chr_empty\n");
    emit_adrp_add(out, "x1", "alya_str_buf", os);
    emit_adrp_add(out, "x2", "alya_str_idx", os);
    out.push_str("    ldr x3, [x2]\n");
    out.push_str("    mov x4, #48000\n");
    out.push_str("    cmp x3, x4\n");
    out.push_str("    b.lt .L_arm64_chr_buf_ok\n");
    out.push_str("    mov x3, #0\n");
    out.push_str(".L_arm64_chr_buf_ok:\n");
    out.push_str("    add x0, x1, x3\n");
    out.push_str("    strb w19, [x0]\n");
    out.push_str("    strb wzr, [x0, #1]\n");
    out.push_str("    add x3, x3, #2\n");
    out.push_str("    add x3, x3, #7\n");
    out.push_str("    and x3, x3, #~7\n");
    out.push_str("    str x3, [x2]\n");
    out.push_str("    b .L_arm64_chr_done\n");
    out.push_str(".L_arm64_chr_empty:\n");
    emit_adrp_add(out, "x0", "alya_str_empty", os);
    out.push_str(".L_arm64_chr_done:\n");
    out.push_str("    ldp x19, x20, [sp, #16]\n");
    out.push_str("    ldp x29, x30, [sp], #32\n");
    out.push_str("    ret\n\n");

    // fn_str
    out.push_str(".align 2\n");
    out.push_str(".global fn_str\n");
    out.push_str("fn_str:\n");
    out.push_str("    stp x29, x30, [sp, #-48]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    stp x19, x20, [sp, #16]\n");
    out.push_str("    stp x21, x22, [sp, #32]\n");
    out.push_str("    mov x19, x0\n");
    emit_adrp_add(out, "x1", "alya_str_buf", os);
    emit_adrp_add(out, "x2", "alya_str_idx", os);
    out.push_str("    ldr x3, [x2]\n");
    out.push_str("    mov x4, #48000\n");
    out.push_str("    cmp x3, x4\n");
    out.push_str("    b.lt .L_arm64_str_buf_ok\n");
    out.push_str("    mov x3, #0\n");
    out.push_str(".L_arm64_str_buf_ok:\n");
    out.push_str("    add x20, x1, x3\n");
    out.push_str("    mov x21, x20\n");
    out.push_str("    cbnz x19, .L_arm64_str_chk_neg\n");
    out.push_str("    mov w5, #'0'\n");
    out.push_str("    strb w5, [x20]\n");
    out.push_str("    strb wzr, [x20, #1]\n");
    out.push_str("    add x20, x20, #2\n");
    out.push_str("    b .L_arm64_str_finish\n");
    out.push_str(".L_arm64_str_chk_neg:\n");
    out.push_str("    cmp x19, #0\n");
    out.push_str("    b.ge .L_arm64_str_pos\n");
    out.push_str("    mov w5, #'-'\n");
    out.push_str("    strb w5, [x20], #1\n");
    out.push_str("    neg x19, x19\n");
    out.push_str(".L_arm64_str_pos:\n");
    out.push_str("    sub sp, sp, #32\n");
    out.push_str("    mov x22, #0\n");
    out.push_str("    mov x6, #10\n");
    out.push_str(".L_arm64_str_div_loop:\n");
    out.push_str("    udiv x7, x19, x6\n");
    out.push_str("    msub x8, x7, x6, x19\n");
    out.push_str("    add w8, w8, #'0'\n");
    out.push_str("    strb w8, [sp, x22]\n");
    out.push_str("    add x22, x22, #1\n");
    out.push_str("    mov x19, x7\n");
    out.push_str("    cbnz x19, .L_arm64_str_div_loop\n");
    out.push_str(".L_arm64_str_copy_loop:\n");
    out.push_str("    sub x22, x22, #1\n");
    out.push_str("    ldrb w8, [sp, x22]\n");
    out.push_str("    strb w8, [x20], #1\n");
    out.push_str("    cbnz x22, .L_arm64_str_copy_loop\n");
    out.push_str("    add sp, sp, #32\n");
    out.push_str("    strb wzr, [x20], #1\n");
    out.push_str(".L_arm64_str_finish:\n");
    emit_adrp_add(out, "x1", "alya_str_buf", os);
    emit_adrp_add(out, "x2", "alya_str_idx", os);
    out.push_str("    sub x3, x20, x1\n");
    out.push_str("    add x3, x3, #7\n");
    out.push_str("    and x3, x3, #~7\n");
    out.push_str("    str x3, [x2]\n");
    out.push_str("    mov x0, x21\n");
    out.push_str("    ldp x21, x22, [sp, #32]\n");
    out.push_str("    ldp x19, x20, [sp, #16]\n");
    out.push_str("    ldp x29, x30, [sp], #48\n");
    out.push_str("    ret\n\n");

    // fn_is_digit
    out.push_str(".align 2\n");
    out.push_str("fn_is_digit:\n");
    out.push_str("    cbz x0, .L_arm64_is_digit_false\n");
    out.push_str("    cmp x0, #256\n");
    out.push_str("    b.lo .L_arm64_is_digit_cmp\n");
    out.push_str("    ldrb w0, [x0]\n");
    out.push_str(".L_arm64_is_digit_cmp:\n");
    out.push_str("    cmp w0, #'0'\n");
    out.push_str("    b.lo .L_arm64_is_digit_false\n");
    out.push_str("    cmp w0, #'9'\n");
    out.push_str("    b.hi .L_arm64_is_digit_false\n");
    out.push_str("    mov x0, #1\n");
    out.push_str("    ret\n");
    out.push_str(".L_arm64_is_digit_false:\n");
    out.push_str("    mov x0, #0\n");
    out.push_str("    ret\n\n");

    // fn_is_alpha
    out.push_str(".align 2\n");
    out.push_str("fn_is_alpha:\n");
    out.push_str("    cbz x0, .L_arm64_is_alpha_false\n");
    out.push_str("    cmp x0, #256\n");
    out.push_str("    b.lo .L_arm64_is_alpha_cmp\n");
    out.push_str("    ldrb w0, [x0]\n");
    out.push_str(".L_arm64_is_alpha_cmp:\n");
    out.push_str("    cmp w0, #'_'\n");
    out.push_str("    b.eq .L_arm64_is_alpha_true\n");
    out.push_str("    cmp w0, #'a'\n");
    out.push_str("    b.lo .L_arm64_is_alpha_upper\n");
    out.push_str("    cmp w0, #'z'\n");
    out.push_str("    b.ls .L_arm64_is_alpha_true\n");
    out.push_str(".L_arm64_is_alpha_upper:\n");
    out.push_str("    cmp w0, #'A'\n");
    out.push_str("    b.lo .L_arm64_is_alpha_false\n");
    out.push_str("    cmp w0, #'Z'\n");
    out.push_str("    b.ls .L_arm64_is_alpha_true\n");
    out.push_str(".L_arm64_is_alpha_false:\n");
    out.push_str("    mov x0, #0\n");
    out.push_str("    ret\n");
    out.push_str(".L_arm64_is_alpha_true:\n");
    out.push_str("    mov x0, #1\n");
    out.push_str("    ret\n\n");

    // fn_is_alnum
    out.push_str(".align 2\n");
    out.push_str("fn_is_alnum:\n");
    out.push_str("    stp x29, x30, [sp, #-32]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    str x19, [sp, #16]\n");
    out.push_str("    mov x19, x0\n");
    out.push_str("    bl fn_is_alpha\n");
    out.push_str("    cbnz x0, .L_arm64_is_alnum_done\n");
    out.push_str("    mov x0, x19\n");
    out.push_str("    bl fn_is_digit\n");
    out.push_str(".L_arm64_is_alnum_done:\n");
    out.push_str("    ldr x19, [sp, #16]\n");
    out.push_str("    ldp x29, x30, [sp], #32\n");
    out.push_str("    ret\n\n");

    // fn_is_space / fn_is_whitespace
    out.push_str(".align 2\n");
    out.push_str("fn_is_whitespace:\n");
    out.push_str("fn_is_space:\n");
    out.push_str("    cbz x0, .L_arm64_is_space_false\n");
    out.push_str("    cmp x0, #256\n");
    out.push_str("    b.lo .L_arm64_is_space_cmp\n");
    out.push_str("    ldrb w0, [x0]\n");
    out.push_str(".L_arm64_is_space_cmp:\n");
    out.push_str("    cmp w0, #' '\n");
    out.push_str("    b.eq .L_arm64_is_space_true\n");
    out.push_str("    cmp w0, #9\n");
    out.push_str("    b.eq .L_arm64_is_space_true\n");
    out.push_str("    cmp w0, #10\n");
    out.push_str("    b.eq .L_arm64_is_space_true\n");
    out.push_str("    cmp w0, #13\n");
    out.push_str("    b.eq .L_arm64_is_space_true\n");
    out.push_str(".L_arm64_is_space_false:\n");
    out.push_str("    mov x0, #0\n");
    out.push_str("    ret\n");
    out.push_str(".L_arm64_is_space_true:\n");
    out.push_str("    mov x0, #1\n");
    out.push_str("    ret\n\n");

    // fn_join
    out.push_str(".global fn_join\n");
    out.push_str("fn_join:\n");
    out.push_str("    stp x29, x30, [sp, #-80]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    stp x19, x20, [sp, #16]\n");
    out.push_str("    stp x21, x22, [sp, #32]\n");
    out.push_str("    stp x23, x24, [sp, #48]\n");
    out.push_str("    stp x25, x26, [sp, #64]\n");
    out.push_str("    mov x19, x0\n"); // arr
    out.push_str("    mov x20, x1\n"); // delim
    out.push_str("    cbz x19, .L_arm64_join_empty\n");
    out.push_str("    ldr x21, [x19]\n"); // arr->len
    out.push_str("    cbz x21, .L_arm64_join_empty\n");
    emit_adrp_add(out, "x22", "alya_str_buf", os);
    emit_adrp_add(out, "x23", "alya_str_idx", os);
    out.push_str("    ldr x24, [x23]\n");
    out.push_str("    mov x9, #48000\n");
    out.push_str("    cmp x24, x9\n");
    out.push_str("    b.lt .L_arm64_join_buf_ok\n");
    out.push_str("    mov x24, #0\n");
    out.push_str(".L_arm64_join_buf_ok:\n");
    out.push_str("    add x25, x22, x24\n"); // write_ptr
    out.push_str("    mov x26, x25\n"); // start_ptr
    out.push_str("    mov x2, #0\n"); // i = 0
    out.push_str(".L_arm64_join_loop:\n");
    out.push_str("    cmp x2, x21\n");
    out.push_str("    b.ge .L_arm64_join_finish\n");
    out.push_str("    cbz x2, .L_arm64_join_copy_elem\n");
    out.push_str("    mov x3, x20\n"); // copy delim
    out.push_str(".L_arm64_join_copy_delim:\n");
    out.push_str("    ldrb w4, [x3], #1\n");
    out.push_str("    cbz w4, .L_arm64_join_copy_elem\n");
    out.push_str("    strb w4, [x25], #1\n");
    out.push_str("    b .L_arm64_join_copy_delim\n");
    out.push_str(".L_arm64_join_copy_elem:\n");
    out.push_str("    ldr x3, [x19, #16]\n"); // arr->data
    out.push_str("    ldr x3, [x3, x2, lsl #3]\n"); // arr->data[i]
    out.push_str(".L_arm64_join_copy_elem_loop:\n");
    out.push_str("    ldrb w4, [x3], #1\n");
    out.push_str("    cbz w4, .L_arm64_join_elem_done\n");
    out.push_str("    strb w4, [x25], #1\n");
    out.push_str("    b .L_arm64_join_copy_elem_loop\n");
    out.push_str(".L_arm64_join_elem_done:\n");
    out.push_str("    add x2, x2, #1\n");
    out.push_str("    b .L_arm64_join_loop\n");
    out.push_str(".L_arm64_join_finish:\n");
    out.push_str("    strb wzr, [x25], #1\n");
    out.push_str("    sub x3, x25, x22\n");
    out.push_str("    add x3, x3, #7\n");
    out.push_str("    and x3, x3, #~7\n");
    out.push_str("    str x3, [x23]\n");
    out.push_str("    mov x0, x26\n");
    out.push_str("    b .L_arm64_join_ret\n");
    out.push_str(".L_arm64_join_empty:\n");
    emit_adrp_add(out, "x0", "alya_str_empty", os);
    out.push_str(".L_arm64_join_ret:\n");
    out.push_str("    ldp x25, x26, [sp, #64]\n");
    out.push_str("    ldp x23, x24, [sp, #48]\n");
    out.push_str("    ldp x21, x22, [sp, #32]\n");
    out.push_str("    ldp x19, x20, [sp, #16]\n");
    out.push_str("    ldp x29, x30, [sp], #80\n");
    out.push_str("    ret\n\n");

    // fn_split
    out.push_str(".global fn_split\n");
    out.push_str("fn_split:\n");
    out.push_str("    stp x29, x30, [sp, #-80]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    stp x19, x20, [sp, #16]\n");
    out.push_str("    stp x21, x22, [sp, #32]\n");
    out.push_str("    stp x23, x24, [sp, #48]\n");
    out.push_str("    stp x25, x26, [sp, #64]\n");
    out.push_str("    mov x19, x0\n"); // str
    out.push_str("    mov x20, x1\n"); // delim
    out.push_str("    mov x0, #0\n");
    out.push_str("    bl alya_array_new\n");
    out.push_str("    mov x21, x0\n"); // arr
                                       // compute delim_len
    out.push_str("    mov x22, #0\n"); // delim_len
    out.push_str(".L_arm64_split_dlen_loop:\n");
    out.push_str("    ldrb w2, [x20, x22]\n");
    out.push_str("    cbz w2, .L_arm64_split_dlen_done\n");
    out.push_str("    add x22, x22, #1\n");
    out.push_str("    b .L_arm64_split_dlen_loop\n");
    out.push_str(".L_arm64_split_dlen_done:\n");
    out.push_str("    cbnz x22, .L_arm64_split_non_empty_delim\n");
    // empty delim: split char by char
    out.push_str("    mov x23, x19\n");
    out.push_str(".L_arm64_split_empty_loop:\n");
    out.push_str("    ldrb w24, [x23], #1\n");
    out.push_str("    cbz w24, .L_arm64_split_ret\n");
    emit_adrp_add(out, "x9", "alya_str_buf", os);
    emit_adrp_add(out, "x10", "alya_str_idx", os);
    out.push_str("    ldr x11, [x10]\n");
    out.push_str("    mov x12, #48000\n");
    out.push_str("    cmp x11, x12\n");
    out.push_str("    b.lt .L_arm64_se1\n");
    out.push_str("    mov x11, #0\n");
    out.push_str(".L_arm64_se1:\n");
    out.push_str("    add x12, x9, x11\n"); // token ptr
    out.push_str("    strb w24, [x12]\n");
    out.push_str("    strb wzr, [x12, #1]\n");
    out.push_str("    add x13, x11, #2\n");
    out.push_str("    add x13, x13, #7\n");
    out.push_str("    and x13, x13, #~7\n");
    out.push_str("    str x13, [x10]\n");
    out.push_str("    mov x0, x21\n");
    out.push_str("    mov x1, x12\n");
    out.push_str("    bl alya_array_push\n");
    out.push_str("    b .L_arm64_split_empty_loop\n");
    // non-empty delim
    out.push_str(".L_arm64_split_non_empty_delim:\n");
    out.push_str("    mov x23, x19\n"); // curr
    out.push_str("    mov x24, x19\n"); // token_start
    out.push_str(".L_arm64_split_main_loop:\n");
    out.push_str("    ldrb w9, [x23]\n");
    out.push_str("    cbz w9, .L_arm64_split_emit_final\n");
    out.push_str("    mov x25, #0\n"); // k = 0
    out.push_str(".L_arm64_split_cmp_loop:\n");
    out.push_str("    cmp x25, x22\n");
    out.push_str("    b.ge .L_arm64_split_matched\n");
    out.push_str("    ldrb w10, [x20, x25]\n");
    out.push_str("    ldrb w11, [x23, x25]\n");
    out.push_str("    cmp w10, w11\n");
    out.push_str("    b.ne .L_arm64_split_cmp_fail\n");
    out.push_str("    add x25, x25, #1\n");
    out.push_str("    b .L_arm64_split_cmp_loop\n");
    out.push_str(".L_arm64_split_cmp_fail:\n");
    out.push_str("    add x23, x23, #1\n");
    out.push_str("    b .L_arm64_split_main_loop\n");
    out.push_str(".L_arm64_split_matched:\n");
    emit_adrp_add(out, "x9", "alya_str_buf", os);
    emit_adrp_add(out, "x10", "alya_str_idx", os);
    out.push_str("    ldr x11, [x10]\n");
    out.push_str("    mov x12, #48000\n");
    out.push_str("    cmp x11, x12\n");
    out.push_str("    b.lt .L_arm64_se2\n");
    out.push_str("    mov x11, #0\n");
    out.push_str(".L_arm64_se2:\n");
    out.push_str("    add x25, x9, x11\n"); // token ptr
    out.push_str("    mov x26, x25\n"); // write ptr
    out.push_str("    mov x2, x24\n"); // src = token_start
    out.push_str(".L_arm64_split_tok_copy:\n");
    out.push_str("    cmp x2, x23\n");
    out.push_str("    b.ge .L_arm64_split_tok_done\n");
    out.push_str("    ldrb w3, [x2], #1\n");
    out.push_str("    strb w3, [x26], #1\n");
    out.push_str("    b .L_arm64_split_tok_copy\n");
    out.push_str(".L_arm64_split_tok_done:\n");
    out.push_str("    strb wzr, [x26], #1\n");
    out.push_str("    sub x13, x26, x9\n");
    out.push_str("    add x13, x13, #7\n");
    out.push_str("    and x13, x13, #~7\n");
    out.push_str("    str x13, [x10]\n");
    out.push_str("    mov x0, x21\n");
    out.push_str("    mov x1, x25\n");
    out.push_str("    bl alya_array_push\n");
    out.push_str("    add x23, x23, x22\n"); // curr += delim_len
    out.push_str("    mov x24, x23\n"); // token_start = curr
    out.push_str("    b .L_arm64_split_main_loop\n");
    out.push_str(".L_arm64_split_emit_final:\n");
    emit_adrp_add(out, "x9", "alya_str_buf", os);
    emit_adrp_add(out, "x10", "alya_str_idx", os);
    out.push_str("    ldr x11, [x10]\n");
    out.push_str("    mov x12, #48000\n");
    out.push_str("    cmp x11, x12\n");
    out.push_str("    b.lt .L_arm64_se3\n");
    out.push_str("    mov x11, #0\n");
    out.push_str(".L_arm64_se3:\n");
    out.push_str("    add x25, x9, x11\n"); // token ptr
    out.push_str("    mov x26, x25\n");
    out.push_str("    mov x2, x24\n"); // token_start
    out.push_str(".L_arm64_split_final_copy:\n");
    out.push_str("    cmp x2, x23\n");
    out.push_str("    b.ge .L_arm64_split_final_done\n");
    out.push_str("    ldrb w3, [x2], #1\n");
    out.push_str("    strb w3, [x26], #1\n");
    out.push_str("    b .L_arm64_split_final_copy\n");
    out.push_str(".L_arm64_split_final_done:\n");
    out.push_str("    strb wzr, [x26], #1\n");
    out.push_str("    sub x13, x26, x9\n");
    out.push_str("    add x13, x13, #7\n");
    out.push_str("    and x13, x13, #~7\n");
    out.push_str("    str x13, [x10]\n");
    out.push_str("    mov x0, x21\n");
    out.push_str("    mov x1, x25\n");
    out.push_str("    bl alya_array_push\n");
    out.push_str(".L_arm64_split_ret:\n");
    out.push_str("    mov x0, x21\n"); // return arr
    out.push_str("    ldp x25, x26, [sp, #64]\n");
    out.push_str("    ldp x23, x24, [sp, #48]\n");
    out.push_str("    ldp x21, x22, [sp, #32]\n");
    out.push_str("    ldp x19, x20, [sp, #16]\n");
    out.push_str("    ldp x29, x30, [sp], #80\n");
    out.push_str("    ret\n\n");

    // fn_get_env
    out.push_str(".align 2\n");
    out.push_str(".global fn_get_env\n");
    out.push_str("fn_get_env:\n");
    out.push_str("    stp x29, x30, [sp, #-48]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    stp x19, x20, [sp, #16]\n");
    out.push_str("    stp x21, x22, [sp, #32]\n");
    out.push_str("    cbz x0, .L_arm64_getenv_empty\n");
    out.push_str(&format!("    bl {}getenv\n", p));
    out.push_str("    cbz x0, .L_arm64_getenv_empty\n");
    out.push_str("    mov x19, x0\n");
    emit_adrp_add(out, "x2", "alya_str_buf", os);
    emit_adrp_add(out, "x3", "alya_str_idx", os);
    out.push_str("    ldr x4, [x3]\n");
    out.push_str("    mov x5, #48000\n");
    out.push_str("    cmp x4, x5\n");
    out.push_str("    b.lt .L_arm64_getenv_buf_ok\n");
    out.push_str("    mov x4, #0\n");
    out.push_str(".L_arm64_getenv_buf_ok:\n");
    out.push_str("    add x20, x2, x4\n");
    out.push_str("    mov x21, x20\n");
    out.push_str(".L_arm64_getenv_copy:\n");
    out.push_str("    ldrb w6, [x19], #1\n");
    out.push_str("    strb w6, [x21], #1\n");
    out.push_str("    cbnz w6, .L_arm64_getenv_copy\n");
    out.push_str("    sub x7, x21, x2\n");
    out.push_str("    add x7, x7, #7\n");
    out.push_str("    and x7, x7, #-8\n");
    out.push_str("    str x7, [x3]\n");
    out.push_str("    mov x0, x20\n");
    out.push_str("    b .L_arm64_getenv_ret\n");
    out.push_str(".L_arm64_getenv_empty:\n");
    emit_adrp_add(out, "x0", "alya_str_empty", os);
    out.push_str(".L_arm64_getenv_ret:\n");
    out.push_str("    ldp x21, x22, [sp, #32]\n");
    out.push_str("    ldp x19, x20, [sp, #16]\n");
    out.push_str("    ldp x29, x30, [sp], #48\n");
    out.push_str("    ret\n\n");

}
