[package]
name = "term_table"
version = "0.1.0"
alya-version = "0.0.5"
entry = "src/lib.alya"
description = "A lightweight Unicode and ANSI table formatting library for Alya"
authors = ["Alya Language Contributors <https://github.com/alya-lang>"]
license = "MIT"
homepage = "https://github.com/alya-lang/alya"
repository = "https://github.com/alya-lang/alya"
keywords = ["alya", "alya-lang", "package", "term_table", "table", "ansi", "unicode", "tui"]

[dependencies]
