use crate::codegen::target::OperatingSystem;

#[rustfmt::skip]
pub fn emit(out: &mut String, os: OperatingSystem) {
    let is_win = matches!(os, OperatingSystem::Windows);
    let p = if matches!(os, OperatingSystem::MacOS) { "_" } else { "" };
    let _ = (is_win, p);

    // fn_file_exists
    out.push_str("fn_file_exists:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    mov 8(%ebp), %eax\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jz .L_x86_fexists_no\n");
    out.push_str("    push $alya_str_mode_rb\n");
    out.push_str("    push 8(%ebp)\n");
    out.push_str("    call fopen\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jz .L_x86_fexists_no\n");
    out.push_str("    push %eax\n");
    out.push_str("    call fclose\n");
    out.push_str("    add $4, %esp\n");
    out.push_str("    mov $1, %eax\n");
    out.push_str("    jmp .L_x86_fexists_end\n");
    out.push_str(".L_x86_fexists_no:\n");
    out.push_str("    xor %eax, %eax\n");
    out.push_str(".L_x86_fexists_end:\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_delete_file / fn_remove_file
    out.push_str(".global fn_delete_file\n");
    out.push_str("fn_delete_file:\n");
    out.push_str(".global fn_remove_file\n");
    out.push_str("fn_remove_file:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    mov 8(%ebp), %eax\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jz .L_x86_fdel_fail\n");
    out.push_str("    push 8(%ebp)\n");
    out.push_str("    call remove\n");
    out.push_str("    add $4, %esp\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jnz .L_x86_fdel_fail\n");
    out.push_str("    mov $1, %eax\n");
    out.push_str("    jmp .L_x86_fdel_end\n");
    out.push_str(".L_x86_fdel_fail:\n");
    out.push_str("    xor %eax, %eax\n");
    out.push_str(".L_x86_fdel_end:\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_write_file
    out.push_str("fn_write_file:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov 8(%ebp), %eax\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jz .L_x86_fwrite_fail\n");
    out.push_str("    push $alya_str_mode_wb\n");
    out.push_str("    push 8(%ebp)\n");
    out.push_str("    call fopen\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jz .L_x86_fwrite_fail\n");
    out.push_str("    mov %eax, %ebx\n");
    out.push_str("    mov 12(%ebp), %esi\n");
    out.push_str("    xor %edi, %edi\n");
    out.push_str("    test %esi, %esi\n");
    out.push_str("    jz .L_x86_fwrite_write\n");
    out.push_str(".L_x86_fwrite_len_loop:\n");
    out.push_str("    cmpb $0, (%esi, %edi)\n");
    out.push_str("    je .L_x86_fwrite_write\n");
    out.push_str("    inc %edi\n");
    out.push_str("    jmp .L_x86_fwrite_len_loop\n");
    out.push_str(".L_x86_fwrite_write:\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %edi\n");
    out.push_str("    push $1\n");
    out.push_str("    push %esi\n");
    out.push_str("    call fwrite\n");
    out.push_str("    add $16, %esp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    call fclose\n");
    out.push_str("    add $4, %esp\n");
    out.push_str("    mov $1, %eax\n");
    out.push_str("    jmp .L_x86_fwrite_end\n");
    out.push_str(".L_x86_fwrite_fail:\n");
    out.push_str("    xor %eax, %eax\n");
    out.push_str(".L_x86_fwrite_end:\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_append_file
    out.push_str(".global fn_append_file\n");
    out.push_str("fn_append_file:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov 8(%ebp), %eax\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jz .L_x86_fapp_fail\n");
    out.push_str("    push $alya_str_mode_ab\n");
    out.push_str("    push 8(%ebp)\n");
    out.push_str("    call fopen\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jz .L_x86_fapp_fail\n");
    out.push_str("    mov %eax, %ebx\n");
    out.push_str("    mov 12(%ebp), %esi\n");
    out.push_str("    xor %edi, %edi\n");
    out.push_str("    test %esi, %esi\n");
    out.push_str("    jz .L_x86_fapp_write\n");
    out.push_str(".L_x86_fapp_len_loop:\n");
    out.push_str("    cmpb $0, (%esi, %edi)\n");
    out.push_str("    je .L_x86_fapp_write\n");
    out.push_str("    inc %edi\n");
    out.push_str("    jmp .L_x86_fapp_len_loop\n");
    out.push_str(".L_x86_fapp_write:\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %edi\n");
    out.push_str("    push $1\n");
    out.push_str("    push %esi\n");
    out.push_str("    call fwrite\n");
    out.push_str("    add $16, %esp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    call fclose\n");
    out.push_str("    add $4, %esp\n");
    out.push_str("    mov $1, %eax\n");
    out.push_str("    jmp .L_x86_fapp_end\n");
    out.push_str(".L_x86_fapp_fail:\n");
    out.push_str("    xor %eax, %eax\n");
    out.push_str(".L_x86_fapp_end:\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_read_file
    out.push_str("fn_read_file:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov 8(%ebp), %eax\n");
    out.push_str("    mov $alya_str_empty, %edi\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jz .L_x86_fread_ret\n");
    out.push_str("    push $alya_str_mode_rb\n");
    out.push_str("    push 8(%ebp)\n");
    out.push_str("    call fopen\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jz .L_x86_fread_ret\n");
    out.push_str("    mov %eax, %ebx\n");
    out.push_str("    push $2\n");
    out.push_str("    push $0\n");
    out.push_str("    push %ebx\n");
    out.push_str("    call fseek\n");
    out.push_str("    add $12, %esp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    call ftell\n");
    out.push_str("    add $4, %esp\n");
    out.push_str("    cmp $0, %eax\n");
    out.push_str("    jl .L_x86_fread_close\n");
    out.push_str("    mov %eax, %esi\n");
    out.push_str("    push $0\n");
    out.push_str("    push $0\n");
    out.push_str("    push %ebx\n");
    out.push_str("    call fseek\n");
    out.push_str("    add $12, %esp\n");
    out.push_str("    lea 1(%esi), %edx\n");
    out.push_str("    push %edx\n");
    out.push_str("    push $1\n");
    out.push_str("    call calloc\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    mov %eax, %edi\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push $1\n");
    out.push_str("    push %edi\n");
    out.push_str("    call fread\n");
    out.push_str("    add $16, %esp\n");
    out.push_str("    movb $0, (%edi, %esi)\n");
    out.push_str(".L_x86_fread_close:\n");
    out.push_str("    push %ebx\n");
    out.push_str("    call fclose\n");
    out.push_str("    add $4, %esp\n");
    out.push_str(".L_x86_fread_ret:\n");
    out.push_str("    mov %edi, %eax\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_file_size
    out.push_str(".global fn_file_size\n");
    out.push_str("fn_file_size:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    mov 8(%ebp), %eax\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jz .L_x86_fsize_fail\n");
    out.push_str("    push $alya_str_mode_rb\n");
    out.push_str("    push 8(%ebp)\n");
    out.push_str("    call fopen\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jz .L_x86_fsize_fail\n");
    out.push_str("    mov %eax, %ebx\n");
    out.push_str("    push $2\n");
    out.push_str("    push $0\n");
    out.push_str("    push %ebx\n");
    out.push_str("    call fseek\n");
    out.push_str("    add $12, %esp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    call ftell\n");
    out.push_str("    add $4, %esp\n");
    out.push_str("    push %eax\n");
    out.push_str("    push %ebx\n");
    out.push_str("    call fclose\n");
    out.push_str("    add $4, %esp\n");
    out.push_str("    pop %eax\n");
    out.push_str("    jmp .L_x86_fsize_end\n");
    out.push_str(".L_x86_fsize_fail:\n");
    out.push_str("    mov $-1, %eax\n");
    out.push_str(".L_x86_fsize_end:\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_make_dir / fn_mkdir
    out.push_str(".global fn_make_dir\n");
    out.push_str("fn_make_dir:\n");
    out.push_str(".global fn_mkdir\n");
    out.push_str("fn_mkdir:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    mov 8(%ebp), %eax\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jz .L_x86_mkdir_fail\n");
    if matches!(os, OperatingSystem::Windows) {
        out.push_str("    push %eax\n");
        out.push_str("    call _mkdir\n");
        out.push_str("    add $4, %esp\n");
    } else {
        out.push_str("    push $511\n");
        out.push_str("    push %eax\n");
        out.push_str("    call mkdir\n");
        out.push_str("    add $8, %esp\n");
    }
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jnz .L_x86_mkdir_fail\n");
    out.push_str("    mov $1, %eax\n");
    out.push_str("    jmp .L_x86_mkdir_end\n");
    out.push_str(".L_x86_mkdir_fail:\n");
    out.push_str("    xor %eax, %eax\n");
    out.push_str(".L_x86_mkdir_end:\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

}
