use crate::codegen::target::OperatingSystem;

#[rustfmt::skip]
pub fn emit(out: &mut String, os: OperatingSystem) {
    let is_win = matches!(os, OperatingSystem::Windows);
    let p = if matches!(os, OperatingSystem::MacOS) { "_" } else { "" };
    let _ = (is_win, p);

    // alya_concat
    out.push_str("alya_concat:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    push %ebx\n");
    out.push_str("    mov 8(%ebp), %esi\n");
    out.push_str("    mov 12(%ebp), %edx\n");
    out.push_str("    mov $alya_str_buf, %ecx\n");
    out.push_str("    mov alya_str_idx, %ebx\n");
    out.push_str("    cmp $48000, %ebx\n");
    out.push_str("    jl .L_x86_concat_ok\n");
    out.push_str("    xor %ebx, %ebx\n");
    out.push_str(".L_x86_concat_ok:\n");
    out.push_str("    lea (%ecx, %ebx), %edi\n");
    out.push_str("    mov %edi, %eax\n");
    out.push_str(".L_x86_copy1:\n");
    out.push_str("    movb (%esi), %bl\n");
    out.push_str("    test %bl, %bl\n");
    out.push_str("    jz .L_x86_copy2_start\n");
    out.push_str("    movb %cl, (%edi)\n");
    out.push_str("    inc %esi\n");
    out.push_str("    inc %edi\n");
    out.push_str("    jmp .L_x86_copy1\n");
    out.push_str(".L_x86_copy2_start:\n");
    out.push_str("    mov %edx, %esi\n");
    out.push_str(".L_x86_copy2:\n");
    out.push_str("    movb (%esi), %bl\n");
    out.push_str("    test %bl, %bl\n");
    out.push_str("    jz .L_x86_concat_end\n");
    out.push_str("    movb %cl, (%edi)\n");
    out.push_str("    inc %esi\n");
    out.push_str("    inc %edi\n");
    out.push_str("    jmp .L_x86_copy2\n");
    out.push_str(".L_x86_concat_end:\n");
    out.push_str("    movb $0, (%edi)\n");
    out.push_str("    inc %edi\n");
    out.push_str("    sub %ecx, %edi\n");
    out.push_str("    add $3, %edi\n");
    out.push_str("    and $-4, %edi\n");
    out.push_str("    mov %edi, alya_str_idx\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_len
    out.push_str("fn_len:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    mov 8(%ebp), %edx\n");
    out.push_str("    xor %eax, %eax\n");
    out.push_str(".L_x86_len_loop:\n");
    out.push_str("    cmpb $0, (%edx, %eax)\n");
    out.push_str("    je .L_x86_len_end\n");
    out.push_str("    inc %eax\n");
    out.push_str("    jmp .L_x86_len_loop\n");
    out.push_str(".L_x86_len_end:\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_ask
    out.push_str("fn_ask:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    push %ebx\n");
    out.push_str("    mov 8(%ebp), %eax\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jz .L_x86_ask_read\n");
    out.push_str("    push %eax\n");
    out.push_str("    push $alya_fmt_prompt\n");
    out.push_str("    call printf\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    push $0\n");
    out.push_str("    call fflush\n");
    out.push_str("    add $4, %esp\n");
    out.push_str(".L_x86_ask_read:\n");
    out.push_str("    mov $alya_str_buf, %ecx\n");
    out.push_str("    mov alya_str_idx, %ebx\n");
    out.push_str("    cmp $48000, %ebx\n");
    out.push_str("    jl .L_x86_ask_buf_ok\n");
    out.push_str("    xor %ebx, %ebx\n");
    out.push_str(".L_x86_ask_buf_ok:\n");
    out.push_str("    lea (%ecx, %ebx), %esi\n");
    out.push_str("    mov %esi, %edi\n");
    out.push_str(".L_x86_ask_loop:\n");
    out.push_str("    call getchar\n");
    out.push_str("    cmp $-1, %eax\n");
    out.push_str("    je .L_x86_ask_done\n");
    out.push_str("    cmp $10, %eax\n");
    out.push_str("    je .L_x86_ask_done\n");
    out.push_str("    cmp $13, %eax\n");
    out.push_str("    je .L_x86_ask_loop\n");
    out.push_str("    movb %al, (%edi)\n");
    out.push_str("    inc %edi\n");
    out.push_str("    jmp .L_x86_ask_loop\n");
    out.push_str(".L_x86_ask_done:\n");
    out.push_str("    movb $0, (%edi)\n");
    out.push_str("    inc %edi\n");
    out.push_str("    sub %ecx, %edi\n");
    out.push_str("    add $3, %edi\n");
    out.push_str("    and $-4, %edi\n");
    out.push_str("    mov %edi, alya_str_idx\n");
    out.push_str("    mov %esi, %eax\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_upper
    out.push_str("fn_upper:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov 8(%ebp), %esi\n");
    out.push_str("    mov $alya_str_buf, %ecx\n");
    out.push_str("    mov alya_str_idx, %ebx\n");
    out.push_str("    cmp $48000, %ebx\n");
    out.push_str("    jl .L_x86_upper_buf_ok\n");
    out.push_str("    xor %ebx, %ebx\n");
    out.push_str(".L_x86_upper_buf_ok:\n");
    out.push_str("    lea (%ecx, %ebx), %edi\n");
    out.push_str("    mov %edi, %eax\n");
    out.push_str(".L_x86_upper_loop:\n");
    out.push_str("    movb (%esi), %dl\n");
    out.push_str("    test %dl, %dl\n");
    out.push_str("    jz .L_x86_upper_done\n");
    out.push_str("    cmpb $'a', %dl\n");
    out.push_str("    jl .L_x86_upper_store\n");
    out.push_str("    cmpb $'z', %dl\n");
    out.push_str("    jg .L_x86_upper_store\n");
    out.push_str("    subb $32, %dl\n");
    out.push_str(".L_x86_upper_store:\n");
    out.push_str("    movb %dl, (%edi)\n");
    out.push_str("    inc %esi\n");
    out.push_str("    inc %edi\n");
    out.push_str("    jmp .L_x86_upper_loop\n");
    out.push_str(".L_x86_upper_done:\n");
    out.push_str("    movb $0, (%edi)\n");
    out.push_str("    inc %edi\n");
    out.push_str("    sub %ecx, %edi\n");
    out.push_str("    add $3, %edi\n");
    out.push_str("    and $-4, %edi\n");
    out.push_str("    mov %edi, alya_str_idx\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_lower
    out.push_str("fn_lower:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov 8(%ebp), %esi\n");
    out.push_str("    mov $alya_str_buf, %ecx\n");
    out.push_str("    mov alya_str_idx, %ebx\n");
    out.push_str("    cmp $48000, %ebx\n");
    out.push_str("    jl .L_x86_lower_buf_ok\n");
    out.push_str("    xor %ebx, %ebx\n");
    out.push_str(".L_x86_lower_buf_ok:\n");
    out.push_str("    lea (%ecx, %ebx), %edi\n");
    out.push_str("    mov %edi, %eax\n");
    out.push_str(".L_x86_lower_loop:\n");
    out.push_str("    movb (%esi), %dl\n");
    out.push_str("    test %dl, %dl\n");
    out.push_str("    jz .L_x86_lower_done\n");
    out.push_str("    cmpb $'A', %dl\n");
    out.push_str("    jl .L_x86_lower_store\n");
    out.push_str("    cmpb $'Z', %dl\n");
    out.push_str("    jg .L_x86_lower_store\n");
    out.push_str("    addb $32, %dl\n");
    out.push_str(".L_x86_lower_store:\n");
    out.push_str("    movb %dl, (%edi)\n");
    out.push_str("    inc %esi\n");
    out.push_str("    inc %edi\n");
    out.push_str("    jmp .L_x86_lower_loop\n");
    out.push_str(".L_x86_lower_done:\n");
    out.push_str("    movb $0, (%edi)\n");
    out.push_str("    inc %edi\n");
    out.push_str("    sub %ecx, %edi\n");
    out.push_str("    add $3, %edi\n");
    out.push_str("    and $-4, %edi\n");
    out.push_str("    mov %edi, alya_str_idx\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_trim
    out.push_str("fn_trim:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov 8(%ebp), %esi\n");
    out.push_str(".L_x86_trim_lws:\n");
    out.push_str("    movb (%esi), %al\n");
    out.push_str("    cmpb $32, %al\n");
    out.push_str("    je .L_x86_trim_lws_inc\n");
    out.push_str("    cmpb $9, %al\n");
    out.push_str("    je .L_x86_trim_lws_inc\n");
    out.push_str("    cmpb $10, %al\n");
    out.push_str("    je .L_x86_trim_lws_inc\n");
    out.push_str("    cmpb $13, %al\n");
    out.push_str("    je .L_x86_trim_lws_inc\n");
    out.push_str("    jmp .L_x86_trim_lws_done\n");
    out.push_str(".L_x86_trim_lws_inc:\n");
    out.push_str("    inc %esi\n");
    out.push_str("    jmp .L_x86_trim_lws\n");
    out.push_str(".L_x86_trim_lws_done:\n");
    out.push_str("    mov %esi, %edx\n");
    out.push_str(".L_x86_trim_find_end:\n");
    out.push_str("    cmpb $0, (%edx)\n");
    out.push_str("    je .L_x86_trim_end_found\n");
    out.push_str("    inc %edx\n");
    out.push_str("    jmp .L_x86_trim_find_end\n");
    out.push_str(".L_x86_trim_end_found:\n");
    out.push_str(".L_x86_trim_tws:\n");
    out.push_str("    cmp %esi, %edx\n");
    out.push_str("    jle .L_x86_trim_copy_start\n");
    out.push_str("    movb -1(%edx), %al\n");
    out.push_str("    cmpb $32, %al\n");
    out.push_str("    je .L_x86_trim_tws_dec\n");
    out.push_str("    cmpb $9, %al\n");
    out.push_str("    je .L_x86_trim_tws_dec\n");
    out.push_str("    cmpb $10, %al\n");
    out.push_str("    je .L_x86_trim_tws_dec\n");
    out.push_str("    cmpb $13, %al\n");
    out.push_str("    je .L_x86_trim_tws_dec\n");
    out.push_str("    jmp .L_x86_trim_copy_start\n");
    out.push_str(".L_x86_trim_tws_dec:\n");
    out.push_str("    dec %edx\n");
    out.push_str("    jmp .L_x86_trim_tws\n");
    out.push_str(".L_x86_trim_copy_start:\n");
    out.push_str("    mov $alya_str_buf, %ecx\n");
    out.push_str("    mov alya_str_idx, %ebx\n");
    out.push_str("    cmp $48000, %ebx\n");
    out.push_str("    jl .L_x86_trim_buf_ok\n");
    out.push_str("    xor %ebx, %ebx\n");
    out.push_str(".L_x86_trim_buf_ok:\n");
    out.push_str("    lea (%ecx, %ebx), %edi\n");
    out.push_str("    mov %edi, %eax\n");
    out.push_str(".L_x86_trim_copy_loop:\n");
    out.push_str("    cmp %edx, %esi\n");
    out.push_str("    jge .L_x86_trim_done\n");
    out.push_str("    movb (%esi), %bl\n");
    out.push_str("    movb %bl, (%edi)\n");
    out.push_str("    inc %esi\n");
    out.push_str("    inc %edi\n");
    out.push_str("    jmp .L_x86_trim_copy_loop\n");
    out.push_str(".L_x86_trim_done:\n");
    out.push_str("    movb $0, (%edi)\n");
    out.push_str("    inc %edi\n");
    out.push_str("    sub %ecx, %edi\n");
    out.push_str("    add $3, %edi\n");
    out.push_str("    and $-4, %edi\n");
    out.push_str("    mov %edi, alya_str_idx\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_contains
    out.push_str("fn_contains:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov 8(%ebp), %esi\n");
    out.push_str("    mov 12(%ebp), %edi\n");
    out.push_str("    cmpb $0, (%edi)\n");
    out.push_str("    je .L_x86_contains_match\n");
    out.push_str(".L_x86_contains_outer:\n");
    out.push_str("    cmpb $0, (%esi)\n");
    out.push_str("    je .L_x86_contains_nomatch\n");
    out.push_str("    mov %esi, %eax\n");
    out.push_str("    mov %edi, %edx\n");
    out.push_str(".L_x86_contains_inner:\n");
    out.push_str("    movb (%edx), %cl\n");
    out.push_str("    test %cl, %cl\n");
    out.push_str("    jz .L_x86_contains_match\n");
    out.push_str("    movb (%eax), %bl\n");
    out.push_str("    cmp %bl, %cl\n");
    out.push_str("    jne .L_x86_contains_next\n");
    out.push_str("    inc %eax\n");
    out.push_str("    inc %edx\n");
    out.push_str("    jmp .L_x86_contains_inner\n");
    out.push_str(".L_x86_contains_next:\n");
    out.push_str("    inc %esi\n");
    out.push_str("    jmp .L_x86_contains_outer\n");
    out.push_str(".L_x86_contains_match:\n");
    out.push_str("    mov $1, %eax\n");
    out.push_str("    jmp .L_x86_contains_end\n");
    out.push_str(".L_x86_contains_nomatch:\n");
    out.push_str("    xor %eax, %eax\n");
    out.push_str(".L_x86_contains_end:\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_substring / fn_substr
    out.push_str("fn_substr:\n");
    out.push_str("fn_substring:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov 8(%ebp), %esi\n");
    out.push_str("    mov 12(%ebp), %edx\n");
    out.push_str("    mov 16(%ebp), %ebx\n");
    out.push_str("    cmp $0, %edx\n");
    out.push_str("    jge .L_x86_sub_adv\n");
    out.push_str("    xor %edx, %edx\n");
    out.push_str(".L_x86_sub_adv:\n");
    out.push_str("    test %edx, %edx\n");
    out.push_str("    jle .L_x86_sub_adv_done\n");
    out.push_str("    cmpb $0, (%esi)\n");
    out.push_str("    je .L_x86_sub_adv_done\n");
    out.push_str("    inc %esi\n");
    out.push_str("    dec %edx\n");
    out.push_str("    jmp .L_x86_sub_adv\n");
    out.push_str(".L_x86_sub_adv_done:\n");
    out.push_str("    mov $alya_str_buf, %ecx\n");
    out.push_str("    mov alya_str_idx, %edx\n");
    out.push_str("    cmp $48000, %edx\n");
    out.push_str("    jl .L_x86_sub_buf_ok\n");
    out.push_str("    xor %edx, %edx\n");
    out.push_str(".L_x86_sub_buf_ok:\n");
    out.push_str("    lea (%ecx, %edx), %edi\n");
    out.push_str("    mov %edi, %eax\n");
    out.push_str(".L_x86_sub_copy:\n");
    out.push_str("    cmpb $0, (%esi)\n");
    out.push_str("    je .L_x86_sub_done\n");
    out.push_str("    test %ebx, %ebx\n");
    out.push_str("    jz .L_x86_sub_done\n");
    out.push_str("    movb (%esi), %dl\n");
    out.push_str("    movb %dl, (%edi)\n");
    out.push_str("    inc %esi\n");
    out.push_str("    inc %edi\n");
    out.push_str("    cmp $0, %ebx\n");
    out.push_str("    jl .L_x86_sub_copy\n");
    out.push_str("    dec %ebx\n");
    out.push_str("    jmp .L_x86_sub_copy\n");
    out.push_str(".L_x86_sub_done:\n");
    out.push_str("    movb $0, (%edi)\n");
    out.push_str("    inc %edi\n");
    out.push_str("    sub %ecx, %edi\n");
    out.push_str("    add $3, %edi\n");
    out.push_str("    and $-4, %edi\n");
    out.push_str("    mov %edi, alya_str_idx\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_char_at
    out.push_str("fn_char_at:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov 8(%ebp), %esi\n");
    out.push_str("    mov 12(%ebp), %edx\n");
    out.push_str("    mov $alya_str_empty, %eax\n");
    out.push_str("    test %esi, %esi\n");
    out.push_str("    jz .L_x86_char_at_end\n");
    out.push_str("    cmp $0, %edx\n");
    out.push_str("    jl .L_x86_char_at_end\n");
    out.push_str(".L_x86_char_at_adv:\n");
    out.push_str("    test %edx, %edx\n");
    out.push_str("    jle .L_x86_char_at_fetch\n");
    out.push_str("    cmpb $0, (%esi)\n");
    out.push_str("    je .L_x86_char_at_end\n");
    out.push_str("    inc %esi\n");
    out.push_str("    dec %edx\n");
    out.push_str("    jmp .L_x86_char_at_adv\n");
    out.push_str(".L_x86_char_at_fetch:\n");
    out.push_str("    movzbl (%esi), %edx\n");
    out.push_str("    test %edx, %edx\n");
    out.push_str("    jz .L_x86_char_at_end\n");
    out.push_str("    mov $alya_str_buf, %ecx\n");
    out.push_str("    mov alya_str_idx, %ebx\n");
    out.push_str("    cmp $48000, %ebx\n");
    out.push_str("    jl .L_x86_char_at_buf_ok\n");
    out.push_str("    xor %ebx, %ebx\n");
    out.push_str(".L_x86_char_at_buf_ok:\n");
    out.push_str("    lea (%ecx, %ebx), %edi\n");
    out.push_str("    mov %edi, %eax\n");
    out.push_str("    movb %dl, (%edi)\n");
    out.push_str("    movb $0, 1(%edi)\n");
    out.push_str("    add $2, %edi\n");
    out.push_str("    sub %ecx, %edi\n");
    out.push_str("    add $3, %edi\n");
    out.push_str("    and $-4, %edi\n");
    out.push_str("    mov %edi, alya_str_idx\n");
    out.push_str(".L_x86_char_at_end:\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_ord / fn_char_code
    out.push_str("fn_char_code:\n");
    out.push_str("fn_ord:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    mov 8(%ebp), %eax\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jz .L_x86_ord_zero\n");
    out.push_str("    cmp $256, %eax\n");
    out.push_str("    jb .L_x86_ord_ret\n");
    out.push_str("    movzbl (%eax), %eax\n");
    out.push_str("    jmp .L_x86_ord_ret\n");
    out.push_str(".L_x86_ord_zero:\n");
    out.push_str("    xor %eax, %eax\n");
    out.push_str(".L_x86_ord_ret:\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_chr / fn_char_from_code
    out.push_str("fn_char_from_code:\n");
    out.push_str("fn_chr:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov 8(%ebp), %edx\n");
    out.push_str("    mov $alya_str_empty, %eax\n");
    out.push_str("    test %edx, %edx\n");
    out.push_str("    jz .L_x86_chr_end\n");
    out.push_str("    cmp $256, %edx\n");
    out.push_str("    jb .L_x86_chr_code\n");
    out.push_str("    movzbl (%edx), %edx\n");
    out.push_str(".L_x86_chr_code:\n");
    out.push_str("    and $255, %edx\n");
    out.push_str("    jz .L_x86_chr_end\n");
    out.push_str("    mov $alya_str_buf, %ecx\n");
    out.push_str("    mov alya_str_idx, %ebx\n");
    out.push_str("    cmp $48000, %ebx\n");
    out.push_str("    jl .L_x86_chr_buf_ok\n");
    out.push_str("    xor %ebx, %ebx\n");
    out.push_str(".L_x86_chr_buf_ok:\n");
    out.push_str("    lea (%ecx, %ebx), %edi\n");
    out.push_str("    mov %edi, %eax\n");
    out.push_str("    movb %dl, (%edi)\n");
    out.push_str("    movb $0, 1(%edi)\n");
    out.push_str("    add $2, %edi\n");
    out.push_str("    sub %ecx, %edi\n");
    out.push_str("    add $3, %edi\n");
    out.push_str("    and $-4, %edi\n");
    out.push_str("    mov %edi, alya_str_idx\n");
    out.push_str(".L_x86_chr_end:\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_str
    out.push_str(".global fn_str\n");
    out.push_str("fn_str:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %edi\n");
    out.push_str("    push %esi\n");
    out.push_str("    mov 8(%ebp), %eax\n");
    out.push_str("    mov $alya_str_buf, %ecx\n");
    out.push_str("    mov alya_str_idx, %ebx\n");
    out.push_str("    cmp $48000, %ebx\n");
    out.push_str("    jl .L_x86_str_buf_ok\n");
    out.push_str("    xor %ebx, %ebx\n");
    out.push_str(".L_x86_str_buf_ok:\n");
    out.push_str("    lea (%ecx, %ebx), %edi\n");
    out.push_str("    mov %edi, %esi\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jnz .L_x86_str_chk_neg\n");
    out.push_str("    movb $'0', (%edi)\n");
    out.push_str("    movb $0, 1(%edi)\n");
    out.push_str("    add $2, %edi\n");
    out.push_str("    jmp .L_x86_str_finish\n");
    out.push_str(".L_x86_str_chk_neg:\n");
    out.push_str("    jns .L_x86_str_pos\n");
    out.push_str("    movb $'-', (%edi)\n");
    out.push_str("    inc %edi\n");
    out.push_str("    neg %eax\n");
    out.push_str(".L_x86_str_pos:\n");
    out.push_str("    xor %ecx, %ecx\n");
    out.push_str("    mov $10, %ebx\n");
    out.push_str(".L_x86_str_div_loop:\n");
    out.push_str("    xor %edx, %edx\n");
    out.push_str("    div %ebx\n");
    out.push_str("    add $'0', %dl\n");
    out.push_str("    push %edx\n");
    out.push_str("    inc %ecx\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jnz .L_x86_str_div_loop\n");
    out.push_str(".L_x86_str_copy_loop:\n");
    out.push_str("    pop %edx\n");
    out.push_str("    movb %dl, (%edi)\n");
    out.push_str("    inc %edi\n");
    out.push_str("    dec %ecx\n");
    out.push_str("    jnz .L_x86_str_copy_loop\n");
    out.push_str("    movb $0, (%edi)\n");
    out.push_str("    inc %edi\n");
    out.push_str(".L_x86_str_finish:\n");
    out.push_str("    mov $alya_str_buf, %ecx\n");
    out.push_str("    sub %ecx, %edi\n");
    out.push_str("    add $3, %edi\n");
    out.push_str("    and $-4, %edi\n");
    out.push_str("    mov %edi, alya_str_idx\n");
    out.push_str("    mov %esi, %eax\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_is_digit
    out.push_str("fn_is_digit:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    mov 8(%ebp), %edx\n");
    out.push_str("    xor %eax, %eax\n");
    out.push_str("    test %edx, %edx\n");
    out.push_str("    jz .L_x86_is_digit_end\n");
    out.push_str("    cmp $256, %edx\n");
    out.push_str("    jb .L_x86_is_digit_cmp\n");
    out.push_str("    movzbl (%edx), %edx\n");
    out.push_str(".L_x86_is_digit_cmp:\n");
    out.push_str("    cmp $'0', %edx\n");
    out.push_str("    jb .L_x86_is_digit_end\n");
    out.push_str("    cmp $'9', %edx\n");
    out.push_str("    ja .L_x86_is_digit_end\n");
    out.push_str("    mov $1, %eax\n");
    out.push_str(".L_x86_is_digit_end:\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_is_alpha
    out.push_str("fn_is_alpha:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    mov 8(%ebp), %edx\n");
    out.push_str("    xor %eax, %eax\n");
    out.push_str("    test %edx, %edx\n");
    out.push_str("    jz .L_x86_is_alpha_end\n");
    out.push_str("    cmp $256, %edx\n");
    out.push_str("    jb .L_x86_is_alpha_cmp\n");
    out.push_str("    movzbl (%edx), %edx\n");
    out.push_str(".L_x86_is_alpha_cmp:\n");
    out.push_str("    cmp $'_', %edx\n");
    out.push_str("    je .L_x86_is_alpha_true\n");
    out.push_str("    cmp $'a', %edx\n");
    out.push_str("    jb .L_x86_is_alpha_upper\n");
    out.push_str("    cmp $'z', %edx\n");
    out.push_str("    jbe .L_x86_is_alpha_true\n");
    out.push_str(".L_x86_is_alpha_upper:\n");
    out.push_str("    cmp $'A', %edx\n");
    out.push_str("    jb .L_x86_is_alpha_end\n");
    out.push_str("    cmp $'Z', %edx\n");
    out.push_str("    jbe .L_x86_is_alpha_true\n");
    out.push_str("    jmp .L_x86_is_alpha_end\n");
    out.push_str(".L_x86_is_alpha_true:\n");
    out.push_str("    mov $1, %eax\n");
    out.push_str(".L_x86_is_alpha_end:\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_is_alnum
    out.push_str("fn_is_alnum:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push 8(%ebp)\n");
    out.push_str("    call fn_is_alpha\n");
    out.push_str("    add $4, %esp\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jnz .L_x86_is_alnum_end\n");
    out.push_str("    push 8(%ebp)\n");
    out.push_str("    call fn_is_digit\n");
    out.push_str("    add $4, %esp\n");
    out.push_str(".L_x86_is_alnum_end:\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_is_space / fn_is_whitespace
    out.push_str("fn_is_whitespace:\n");
    out.push_str("fn_is_space:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    mov 8(%ebp), %edx\n");
    out.push_str("    xor %eax, %eax\n");
    out.push_str("    test %edx, %edx\n");
    out.push_str("    jz .L_x86_is_space_end\n");
    out.push_str("    cmp $256, %edx\n");
    out.push_str("    jb .L_x86_is_space_cmp\n");
    out.push_str("    movzbl (%edx), %edx\n");
    out.push_str(".L_x86_is_space_cmp:\n");
    out.push_str("    cmp $' ', %edx\n");
    out.push_str("    je .L_x86_is_space_true\n");
    out.push_str("    cmp $'\\t', %edx\n");
    out.push_str("    je .L_x86_is_space_true\n");
    out.push_str("    cmp $'\\n', %edx\n");
    out.push_str("    je .L_x86_is_space_true\n");
    out.push_str("    cmp $'\\r', %edx\n");
    out.push_str("    je .L_x86_is_space_true\n");
    out.push_str("    jmp .L_x86_is_space_end\n");
    out.push_str(".L_x86_is_space_true:\n");
    out.push_str("    mov $1, %eax\n");
    out.push_str(".L_x86_is_space_end:\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_join
    out.push_str(".global fn_join\n");
    out.push_str("fn_join:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    sub $16, %esp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov 8(%ebp), %eax\n");
    out.push_str("    mov %eax, -8(%ebp)\n"); // arr
    out.push_str("    mov 12(%ebp), %eax\n");
    out.push_str("    mov %eax, -12(%ebp)\n"); // delim
    out.push_str("    mov -8(%ebp), %esi\n");
    out.push_str("    test %esi, %esi\n");
    out.push_str("    jz .L_x86_join_empty\n");
    out.push_str("    mov (%esi), %eax\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jz .L_x86_join_empty\n");
    out.push_str("    mov $alya_str_buf, %ecx\n");
    out.push_str("    mov alya_str_idx, %ebx\n");
    out.push_str("    cmp $48000, %ebx\n");
    out.push_str("    jl .L_x86_join_buf_ok\n");
    out.push_str("    xor %ebx, %ebx\n");
    out.push_str(".L_x86_join_buf_ok:\n");
    out.push_str("    lea (%ecx, %ebx), %edi\n");
    out.push_str("    mov %edi, -4(%ebp)\n"); // start_ptr
    out.push_str("    movl $0, -16(%ebp)\n"); // i = 0
    out.push_str(".L_x86_join_loop:\n");
    out.push_str("    mov -8(%ebp), %esi\n");
    out.push_str("    mov -16(%ebp), %eax\n");
    out.push_str("    cmp (%esi), %eax\n");
    out.push_str("    jge .L_x86_join_finish\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jz .L_x86_join_copy_elem\n");
    out.push_str("    mov -12(%ebp), %esi\n"); // copy delim
    out.push_str(".L_x86_join_copy_delim:\n");
    out.push_str("    movb (%esi), %al\n");
    out.push_str("    test %al, %al\n");
    out.push_str("    jz .L_x86_join_copy_elem\n");
    out.push_str("    movb %al, (%edi)\n");
    out.push_str("    inc %esi\n");
    out.push_str("    inc %edi\n");
    out.push_str("    jmp .L_x86_join_copy_delim\n");
    out.push_str(".L_x86_join_copy_elem:\n");
    out.push_str("    mov -8(%ebp), %esi\n");
    out.push_str("    mov 8(%esi), %esi\n");
    out.push_str("    mov -16(%ebp), %eax\n");
    out.push_str("    mov (%esi, %eax, 4), %esi\n");
    out.push_str(".L_x86_join_copy_elem_loop:\n");
    out.push_str("    movb (%esi), %al\n");
    out.push_str("    test %al, %al\n");
    out.push_str("    jz .L_x86_join_elem_done\n");
    out.push_str("    movb %al, (%edi)\n");
    out.push_str("    inc %esi\n");
    out.push_str("    inc %edi\n");
    out.push_str("    jmp .L_x86_join_copy_elem_loop\n");
    out.push_str(".L_x86_join_elem_done:\n");
    out.push_str("    incl -16(%ebp)\n");
    out.push_str("    jmp .L_x86_join_loop\n");
    out.push_str(".L_x86_join_finish:\n");
    out.push_str("    movb $0, (%edi)\n");
    out.push_str("    inc %edi\n");
    out.push_str("    mov $alya_str_buf, %ecx\n");
    out.push_str("    sub %ecx, %edi\n");
    out.push_str("    add $3, %edi\n");
    out.push_str("    and $-4, %edi\n");
    out.push_str("    mov %edi, alya_str_idx\n");
    out.push_str("    mov -4(%ebp), %eax\n");
    out.push_str("    jmp .L_x86_join_ret\n");
    out.push_str(".L_x86_join_empty:\n");
    out.push_str("    mov $alya_str_empty, %eax\n");
    out.push_str(".L_x86_join_ret:\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_split
    out.push_str(".global fn_split\n");
    out.push_str("fn_split:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    sub $32, %esp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov 8(%ebp), %eax\n");
    out.push_str("    mov %eax, -4(%ebp)\n"); // str
    out.push_str("    mov 12(%ebp), %eax\n");
    out.push_str("    mov %eax, -8(%ebp)\n"); // delim
    out.push_str("    push $0\n");
    out.push_str("    call alya_array_new\n");
    out.push_str("    add $4, %esp\n");
    out.push_str("    mov %eax, -12(%ebp)\n"); // arr
    out.push_str("    mov -8(%ebp), %esi\n");
    out.push_str("    xor %ecx, %ecx\n");
    out.push_str(".L_x86_split_dlen_loop:\n");
    out.push_str("    cmpb $0, (%esi, %ecx)\n");
    out.push_str("    je .L_x86_split_dlen_done\n");
    out.push_str("    inc %ecx\n");
    out.push_str("    jmp .L_x86_split_dlen_loop\n");
    out.push_str(".L_x86_split_dlen_done:\n");
    out.push_str("    mov %ecx, -16(%ebp)\n"); // delim_len
    out.push_str("    test %ecx, %ecx\n");
    out.push_str("    jnz .L_x86_split_non_empty_delim\n");
    out.push_str("    mov -4(%ebp), %esi\n"); // empty delim
    out.push_str(".L_x86_split_empty_loop:\n");
    out.push_str("    movb (%esi), %al\n");
    out.push_str("    test %al, %al\n");
    out.push_str("    jz .L_x86_split_ret\n");
    out.push_str("    mov $alya_str_buf, %ecx\n");
    out.push_str("    mov alya_str_idx, %ebx\n");
    out.push_str("    cmp $48000, %ebx\n");
    out.push_str("    jl .L_x86_se1\n");
    out.push_str("    xor %ebx, %ebx\n");
    out.push_str(".L_x86_se1:\n");
    out.push_str("    lea (%ecx, %ebx), %edi\n");
    out.push_str("    mov %edi, %edx\n");
    out.push_str("    movb %al, (%edi)\n");
    out.push_str("    movb $0, 1(%edi)\n");
    out.push_str("    add $2, %edi\n");
    out.push_str("    sub %ecx, %edi\n");
    out.push_str("    add $3, %edi\n");
    out.push_str("    and $-4, %edi\n");
    out.push_str("    mov %edi, alya_str_idx\n");
    out.push_str("    push %edx\n");
    out.push_str("    push -12(%ebp)\n");
    out.push_str("    call alya_array_push\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    inc %esi\n");
    out.push_str("    jmp .L_x86_split_empty_loop\n");
    out.push_str(".L_x86_split_non_empty_delim:\n");
    out.push_str("    mov -4(%ebp), %eax\n");
    out.push_str("    mov %eax, -20(%ebp)\n"); // curr
    out.push_str("    mov %eax, -24(%ebp)\n"); // token_start
    out.push_str(".L_x86_split_main_loop:\n");
    out.push_str("    mov -20(%ebp), %esi\n");
    out.push_str("    cmpb $0, (%esi)\n");
    out.push_str("    je .L_x86_split_emit_final\n");
    out.push_str("    mov -16(%ebp), %ecx\n"); // delim_len
    out.push_str("    mov -8(%ebp), %edx\n"); // delim
    out.push_str("    xor %ebx, %ebx\n"); // k = 0
    out.push_str(".L_x86_split_cmp_loop:\n");
    out.push_str("    cmp %ecx, %ebx\n");
    out.push_str("    jge .L_x86_split_matched\n");
    out.push_str("    movb (%edx, %ebx), %al\n");
    out.push_str("    cmpb %al, (%esi, %ebx)\n");
    out.push_str("    jne .L_x86_split_cmp_fail\n");
    out.push_str("    inc %ebx\n");
    out.push_str("    jmp .L_x86_split_cmp_loop\n");
    out.push_str(".L_x86_split_cmp_fail:\n");
    out.push_str("    incl -20(%ebp)\n");
    out.push_str("    jmp .L_x86_split_main_loop\n");
    out.push_str(".L_x86_split_matched:\n");
    out.push_str("    mov $alya_str_buf, %ecx\n");
    out.push_str("    mov alya_str_idx, %ebx\n");
    out.push_str("    cmp $48000, %ebx\n");
    out.push_str("    jl .L_x86_se2\n");
    out.push_str("    xor %ebx, %ebx\n");
    out.push_str(".L_x86_se2:\n");
    out.push_str("    lea (%ecx, %ebx), %edi\n");
    out.push_str("    mov %edi, -28(%ebp)\n");
    out.push_str("    mov -24(%ebp), %esi\n");
    out.push_str("    mov -20(%ebp), %edx\n");
    out.push_str(".L_x86_split_tok_copy:\n");
    out.push_str("    cmp %edx, %esi\n");
    out.push_str("    jge .L_x86_split_tok_done\n");
    out.push_str("    movb (%esi), %al\n");
    out.push_str("    movb %al, (%edi)\n");
    out.push_str("    inc %esi\n");
    out.push_str("    inc %edi\n");
    out.push_str("    jmp .L_x86_split_tok_copy\n");
    out.push_str(".L_x86_split_tok_done:\n");
    out.push_str("    movb $0, (%edi)\n");
    out.push_str("    inc %edi\n");
    out.push_str("    sub %ecx, %edi\n");
    out.push_str("    add $3, %edi\n");
    out.push_str("    and $-4, %edi\n");
    out.push_str("    mov %edi, alya_str_idx\n");
    out.push_str("    push -28(%ebp)\n");
    out.push_str("    push -12(%ebp)\n");
    out.push_str("    call alya_array_push\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    mov -16(%ebp), %eax\n");
    out.push_str("    add %eax, -20(%ebp)\n");
    out.push_str("    mov -20(%ebp), %eax\n");
    out.push_str("    mov %eax, -24(%ebp)\n");
    out.push_str("    jmp .L_x86_split_main_loop\n");
    out.push_str(".L_x86_split_emit_final:\n");
    out.push_str("    mov $alya_str_buf, %ecx\n");
    out.push_str("    mov alya_str_idx, %ebx\n");
    out.push_str("    cmp $48000, %ebx\n");
    out.push_str("    jl .L_x86_se3\n");
    out.push_str("    xor %ebx, %ebx\n");
    out.push_str(".L_x86_se3:\n");
    out.push_str("    lea (%ecx, %ebx), %edi\n");
    out.push_str("    mov %edi, -28(%ebp)\n");
    out.push_str("    mov -24(%ebp), %esi\n");
    out.push_str("    mov -20(%ebp), %edx\n");
    out.push_str(".L_x86_split_final_copy:\n");
    out.push_str("    cmp %edx, %esi\n");
    out.push_str("    jge .L_x86_split_final_done\n");
    out.push_str("    movb (%esi), %al\n");
    out.push_str("    movb %al, (%edi)\n");
    out.push_str("    inc %esi\n");
    out.push_str("    inc %edi\n");
    out.push_str("    jmp .L_x86_split_final_copy\n");
    out.push_str(".L_x86_split_final_done:\n");
    out.push_str("    movb $0, (%edi)\n");
    out.push_str("    inc %edi\n");
    out.push_str("    sub %ecx, %edi\n");
    out.push_str("    add $3, %edi\n");
    out.push_str("    and $-4, %edi\n");
    out.push_str("    mov %edi, alya_str_idx\n");
    out.push_str("    push -28(%ebp)\n");
    out.push_str("    push -12(%ebp)\n");
    out.push_str("    call alya_array_push\n");
    out.push_str("    add $8, %esp\n");
    out.push_str(".L_x86_split_ret:\n");
    out.push_str("    mov -12(%ebp), %eax\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_get_env
    out.push_str(".global fn_get_env\n");
    out.push_str("fn_get_env:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %edi\n");
    out.push_str("    push %esi\n");
    out.push_str("    mov 8(%ebp), %eax\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jz .L_x86_getenv_empty\n");
    out.push_str("    push %eax\n");
    out.push_str("    call getenv\n");
    out.push_str("    add $4, %esp\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jz .L_x86_getenv_empty\n");
    out.push_str("    mov %eax, %esi\n");
    out.push_str("    mov $alya_str_buf, %ebx\n");
    out.push_str("    mov alya_str_idx, %edi\n");
    out.push_str("    cmp $48000, %edi\n");
    out.push_str("    jl .L_x86_getenv_buf_ok\n");
    out.push_str("    xor %edi, %edi\n");
    out.push_str(".L_x86_getenv_buf_ok:\n");
    out.push_str("    lea (%ebx, %edi), %edx\n");
    out.push_str(".L_x86_getenv_copy:\n");
    out.push_str("    movb (%esi), %al\n");
    out.push_str("    movb %al, (%ebx, %edi)\n");
    out.push_str("    testb %al, %al\n");
    out.push_str("    jz .L_x86_getenv_done\n");
    out.push_str("    inc %esi\n");
    out.push_str("    inc %edi\n");
    out.push_str("    jmp .L_x86_getenv_copy\n");
    out.push_str(".L_x86_getenv_done:\n");
    out.push_str("    inc %edi\n");
    out.push_str("    add $3, %edi\n");
    out.push_str("    and $-4, %edi\n");
    out.push_str("    mov %edi, alya_str_idx\n");
    out.push_str("    mov %edx, %eax\n");
    out.push_str("    jmp .L_x86_getenv_ret\n");
    out.push_str(".L_x86_getenv_empty:\n");
    out.push_str("    mov $alya_str_empty, %eax\n");
    out.push_str(".L_x86_getenv_ret:\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

}
